### ISSUE TITLE
WSL support of bubblewrap

### ISSUE THREAD

**Issue by mprevot** [containers/bubblewrap#272]
To date, bubble wrap doesn't work on WSL.

Could a bubblewrap developer enumerate things needed to have it work ? so we make a feature request at MSFT.

Regards

**Comment by mwleeds** [comment]
possibly relevant to this: https://blogs.gnome.org/alexl/2018/09/17/flatpak-on-windows/

**Comment by aaruni96** [comment]
As of bubblewrap 0.8.0 / WSL2 / Windows 10 (22H2, released in November 2022), this seems to not be a problem anymore ?
All tests appear to pass, and at least in my use cases, things seem to work without problems.

**Comment by smcv** [comment]
My understanding is that WSL2 is a virtual machine running an actual Linux kernel, so most syscalls should work correctly in WSL2.

Conversely, WSL1 was like Wine in reverse, implementing a subset of Linux syscalls on the Windows kernel, which means it will probably never support running namespace-based tools like bubblewrap.

If bubblewrap works in WSL2, I think we can close this as "not going to happen" for WSL1: it is not up to the bubblewrap maintainers whether WSL1 implements the syscalls that bubblewrap makes.

> Could a bubblewrap developer enumerate things needed to have it work ? so we make a feature request at MSFT

If someone wants this, please see the source code for details. (It isn't actually very large.)

**Comment by kudorgyozo** [comment]
This was the first result in google for searching on how to install bubblewrap in wsl. I have no idea what bwrap is, but I get a warning every time from codex.

https://developers.openai.com/codex/concepts/sandboxing#prerequisites
sudo apt install bubblewrap
