### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by clarus** [containers/bubblewrap#315]
As I have read, this package should preferably be installed using one's system package manager. I would still add some install instructions in the `README.md` for those who want to compile from the sources, such as:

```sh
env NOCONFIGURE=1 ./autogen.sh
mkdir build
cd build && ../configure
make -j 2
sudo install -c bwrap /usr/local/bin/
```

(procedure lazily extracted from the `.travis.yml`).

Thanks!

**Comment by clarus** [comment]
For information, I have found the install instruction in this answer: https://github.com/ocaml/opam/issues/3424#issuecomment-450786508

**Comment by TingPing** [comment]
> For information, I have found the install instruction in this answer: [ocaml/opam#3424 (comment)](https://github.com/ocaml/opam/issues/3424#issuecomment-450786508)

It really should just run `sudo make install` if it wants to broadly work since many distros require suid.

**Comment by phlummox** [comment]
Hi - is there any progress on this? I'm happy to make a pull request adding those instructions to the README. Even better, I think, would be to add an INSTALL file giving installation instructions - but I'm happy with whichever you prefer.
