### ISSUE TITLE
Move to containers/ github organization

### ISSUE THREAD

**Issue by cgwalters** [containers/bubblewrap#326]
We would like to sunset the projectatomic/ github organization.

I like to describe bubblewrap's modern usage (ignoring the setuid support) as a thin wrapper (implemented in C) around the kernel user namespace support, without cgroups.  In other words, a subset of `runc` for example.

The [containers](https://github.com/containers/) organization has been suggested as a home.  Any further thoughts on that, opposition, approval?

**Comment by rhatdan** [comment]
In my opinion bubblewrap belongs on the containers organization, and we would welcome it.

**Comment by alexlarsson** [comment]
Makes sense to me

**Comment by cgwalters** [comment]
OK, @rhatdan - you're an admin in both organizations right?  Can you [do the transfer](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-organization) ?

**Comment by rhatdan** [comment]
Done
