### ISSUE TITLE
Question: Test that bubblewrap is used

### ISSUE THREAD

**Issue by Jacalz** [containers/bubblewrap#339]
Hi there.
I am packaging libwebkit-gtk with subprocess sandboxing using bubblewrap, but I don't know how I could make sure to test that bubblewrap is being used. Do you have any good way of testing that your sandbox is being used, that I could use?

**Comment by sunaku** [comment]
Assuming that `--unshare-pid` isn't specified, couldn't you just check for a `bwrap` ancestor process?

For example, when I run `pstree` inside a bubblewrap sandbox, I can trace its ancestry back to `bwrap`:

```sh
$ bwrap --bind / / bash
user@host:~$ pstree -p -h | less +/$$
runit(1)─┬─...
         ├─tmux: server(1610)─┬─...
         │                    └─zsh(6278)─┬─bwrap(28501)───bash(28502)───pstree(28505) 
        ...                              ...
user@host:~$
```

Here, `bash(28502)` denotes my shell inside the bubblewrap sandbox and its parent is `bwrap(28501)`.

**Comment by TingPing** [comment]
Indeed that works, in this case the `WebKitWebProcess` will be a child of `bwrap`.

**Comment by Jacalz** [comment]
Thank you. Would the following picture mean that `bwrap` is being used?
![image](https://user-images.githubusercontent.com/25466657/71263283-e892c280-2341-11ea-8f58-042edd064ef8.png)
