### ISSUE TITLE
amicontained shows that --dev re-adds all capabilities

### ISSUE THREAD

**Issue by Maryse47** [containers/bubblewrap#350]
[amicontained](https://github.com/genuinetools/amicontained) is a tool that shows what security features are enabled inside sandbox.

Simple run with `bwrap --bind / / amicontained shows` that all capabilities are dropped:
```
Container Runtime: not-found
Has Namespaces:
        pid: true
        user: true
User Namespace Mappings:
        Container -> 1000       Host -> 1000    Range -> 1
AppArmor Profile: unconfined
Capabilities:
Seccomp: disabled
Blocked Syscalls (23):
        SYSLOG SETSID SETGROUPS VHANGUP PIVOT_ROOT ACCT SETTIMEOFDAY UMOUNT2 SWAPON SWAPOFF REBOOT SETHOSTNAME SETDOMAINNAME INIT_MODULE DELETE_MODULE LOOKUP_DCOOKIE FUTIMESAT UTIMENSAT PERF_EVENT_OPEN FANOTIFY_INIT OPEN_BY_HANDLE_AT FINIT_MODULE BPF
```
Adding capabilities with `bwrap --bind / / --cap-add cap_sys_admin amicontained` works:
```
Container Runtime: not-found
Has Namespaces:
        pid: true
        user: true
User Namespace Mappings:
        Container -> 1000       Host -> 1000    Range -> 1
AppArmor Profile: unconfined
Capabilities:
        BOUNDING -> sys_admin
        AMBIENT -> sys_admin
Seccomp: disabled
Blocked Syscalls (21):
        SYSLOG SETSID SETGROUPS VHANGUP ACCT SETTIMEOFDAY SWAPON SWAPOFF REBOOT SETHOSTNAME SETDOMAINNAME INIT_MODULE DELETE_MODULE LOOKUP_DCOOKIE FUTIMESAT UTIMENSAT PERF_EVENT_OPEN FANOTIFY_INIT OPEN_BY_HANDLE_AT FINIT_MODULE BPF
```
but adding `--dev` results with **adding all capabilities**
```
Container Runtime: not-found
Has Namespaces:
        pid: true
        user: true
User Namespace Mappings:
        Container -> 1000       Host -> 0       Range -> 1
AppArmor Profile: unconfined
Capabilities:
        BOUNDING -> chown dac_override dac_read_search fowner fsetid kill setgid setuid setpcap linux_immutable net_bind_service net_broadcast net_admin net_raw ipc_lock ipc_owner sys_module sys_rawio sys_chroot sys_ptrace sys_pacct sys_admin sys_boot sys_nice sys_resource sys_time sys_tty_config mknod lease audit_write audit_control setfcap mac_override mac_admin syslog wake_alarm block_suspend audit_read
Seccomp: disabled
Blocked Syscalls (23):
        SYSLOG SETSID SETGROUPS VHANGUP PIVOT_ROOT ACCT SETTIMEOFDAY UMOUNT2 SWAPON SWAPOFF REBOOT SETHOSTNAME SETDOMAINNAME INIT_MODULE DELETE_MODULE LOOKUP_DCOOKIE FUTIMESAT UTIMENSAT PERF_EVENT_OPEN FANOTIFY_INIT OPEN_BY_HANDLE_AT FINIT_MODULE BPF
```
is it expected behavior or a bug in either of bubblewrap or amicontained?

**Comment by smcv** [comment]
> adding `--dev`

Please quote the whole command-line you used?

**Comment by smcv** [comment]
Also, are you using a setuid-root `bwrap` on an OS like Debian where this is required, or a non-setuid-root `bwrap` on an OS like Fedora or Ubuntu where unprivileged users can create user namespaces? `bwrap` needs to do rather different things in these two cases.

Do you get the same results if you use `setpriv --dump` (from util-linux) instead of `amicontained`? `setpriv` is a standard tool that should exist in all recent Linux distributions.

**Comment by Maryse47** [comment]
> Please quote the whole command-line you used?

Sorry I thought I did... it's `bwrap --bind / / --dev /dev <command>`

> Also, are you using a setuid-root bwrap on an OS like Debian where this is required, or a non-setuid-root bwrap on an OS like Fedora or Ubuntu where unprivileged users can create user namespaces? bwrap needs to do rather different things in these two cases.

I'm using non-setuid bwrap on Arch Linux with unprivileged user namespaces enabled with `kernel.unprivileged_userns_clone=1` sysctl.

> Do you get the same results if you use setpriv --dump (from util-linux) instead of amicontained? setpriv is a standard tool that should exist in all recent Linux distributions.

Yes, so this rules-out amicontained issue:
```

bwrap --bind / / bash
$ setpriv --dump
uid: 1000
euid: 1000
gid: 100
egid: 100
Supplementary groups: 65534,65534,100,65534,65534,65534
no_new_privs: 1
Inheritable capabilities: [none]
Ambient capabilities: [none]
Capability bounding set: [none]
Securebits: [none]
Parent death signal: [none]
AppArmor profile: unconfine

bwrap --bind / / --dev /dev bash
$ setpriv --dump
uid: 1000
euid: 1000
gid: 100
egid: 100
Supplementary groups: 65534,65534,100,65534,65534,65534
no_new_privs: 1
Inheritable capabilities: [none]
Ambient capabilities: [none]
Capability bounding set: chown,dac_override,dac_read_search,fowner,fsetid,kill,setgid,setuid,setpcap,linux_immutable,net_bind_service,net_broadcast,net_admin,net_raw,ipc_lock,ipc_owner,sys_module,sys_rawio,sys_chroot,sys_ptrace,sys_pacct,sys_admin,sys_boot,sys_nice,sys_resource,sys_time,sys_tty_config,mknod,lease,audit_write,audit_control,setfcap,mac_override,mac_admin,syslog,wake_alarm,block_suspend,audit_read
Securebits: [none]
Parent death signal: [none]
AppArmor profile: unconfined

```

**Comment by smcv** [comment]
The same thing doesn't seem to happen with a setuid-root bwrap on a kernel that needs it to be setuid (Debian with `kernel.unprivileged_userns_clone=0` - I think Arch uses the same kernel patch for this as Debian).

```
$ bwrap --bind / / setpriv --dump
...
Capability bounding set: [none]
...
$ bwrap --bind / / --dev /dev setpriv --dump
...
Capability bounding set: [none]
...
```

If I use a non-setuid copy of bwrap and enable `kernel.unprivileged_userns_clone=1`, I get the same result as you. That seems like a bug.

However, note that the child process still has `NO_NEW_PRIVS`, so I don't think the larger capability bounding set in your case actually has any practical impact. The capability bounding set is the set of capabilities that it might be given by running an executable with setuid root or file capabilities, but `NO_NEW_PRIVS` disables transitions that give you new privileges, including setuid and file capabilities, so you're not going to receive those as effective capabilities either way.

For example, I can't exercise `CAP_NET_RAW` in a bubblewrap sandbox:

```
$ getcap /bin/ping
/bin/ping = cap_net_raw+ep
$ ~/tmp/nonsetuid-bwrap --bind / / --dev /dev /bin/ping 8.8.8.8
ping: socket: Operation not permitted
```

**Comment by alexlarsson** [comment]
This seems to be caused by the opt_needs_devpts workaround. I.e. we create a two layered user namespace, the first on mapping the host uid to 0 so we can mount devpts, and the second to map back to the original numerical id. I tested this by setting opt_needs_devpts to TRUE without using --dev.

This is due to the second unshare (CLONE_NEWNS) where we remap the uids again, which clears the capability bounding set. I belive we should clear it again here to be consistent, but as @smcv said its not really a problem as no_new_privs is a superset of capability bounding
