### ISSUE TITLE
Tests failing with the new libcap

### ISSUE THREAD

**Issue by seb128** [containers/bubblewrap#353]
The Ubuntu autopkgtest bubblewrap test started failing since a recent libcap update

```
# Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
# Ambient set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fsetid,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
# Securebits: 00/0x0/1'b0
#  secure-noroot: no (unlocked)
#  secure-no-suid-fixup: no (unlocked)
#  secure-keep-caps: no (unlocked)
#  secure-no-ambient-raise: no (unlocked)
# uid=0(root) euid=0(root)
# gid=0(root)
# groups=0(root)
# Guessed mode: UNCERTAIN (0)
+ fatal 'File '\''caps.test'\'' matches regexp '\''^Current: =.*cap_kill'\'''
+ echo File ''\''caps.test'\''' matches regexp ''\''^Current:' '=.*cap_kill'\'''
File 'caps.test' matches regexp '^Current: =.*cap_kill'
+ exit 1
```

The issue started with https://git.kernel.org/pub/scm/libs/libcap/libcap.git/commit/?id=afef3ef1

log can be found on https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-focal/focal/amd64/b/bubblewrap/20200217_205507_3784d@/log.gz

'Change the definition of 'all' to be all named capabilities.

This change concerns the text formating functions:

  C:  cap_to_text(), cap_from_text()
 Go:  cap.FromText() and cap.Set.String()

Prior to this commit, "all" meant every bit of the capability vector
was raised - both named, and unnamed capabilities. 
...'

Unsure that can be considered as a libcap bug or if the bubblewrap tests need to be updated?

**Comment by ckastner** [comment]
This was also reported in Debian as bug [951577](https://bugs.debian.org/951577).

Previously, after `-cap-drop CAP_KILL
--cap-drop CAP_FOWNER`, Current was printed as

```
Current: = cap_chown,xxx,cap_audit_read+eip
```

where +eip adds all capabilities (abbreviated xxx) except the dropped ones.

With the most recent `libcap`, it prints

```
Current: =eip cap_fowner,cap_kill-eip
```
where, starting with the set of all capabilities, the two get dropped with `-iep`.
