### ISSUE TITLE
Gracefully degrade if sysctl kernel.unprivileged_userns_clone=0

### ISSUE THREAD

**Issue by probonopd** [containers/bubblewrap#360]
Unfortunately some distributions such as Debian are still shipping with `sysctl kernel.unprivileged_userns_clone=0` by default. Is there any way to gracefully degrade bubblewrap to another mechanism for creating a "fake namespace", e.g., similar to Chromium which has `--no-sandbox` so that the application can still run in such circumstances?

My use case:
As a user, I would like to run a Flatpak'd application using bubblewrap on a system that does not have Flatpak nor bubblewrap installed in the system, and where I do not have root rights.

Reference:
https://github.com/AppImage/AppImageKit/issues/297#issuecomment-602230175

**Comment by smcv** [comment]
> As a user, I would like to run a Flatpak'd application using bubblewrap on a system that does not have Flatpak nor bubblewrap installed in the system, and where I do not have root rights.

You can't. Some of the things that Flatpak asks bubblewrap to do are just not possible without either having a setuid root bubblewrap, or a kernel that allows unprivileged users to create new user namespaces.

**Comment by probonopd** [comment]
Thanks for the clarification @smcv. Looks like I'll have to investigate other ways such as [proot](https://proot-me.github.io/), [fakechroot](https://github.com/dex4er/fakechroot/wiki) and/or `LD_PRELOAD` and/or a patched ld-linux for creating a "fake namespace" in situations where bubblewrap cannot be used.

Closing this issue here since bubblewrap cannot do this. If anyone has any helpful suggestions for alternatives, I'd be happy if you could share them here. Thank you.
