### ISSUE TITLE
[Question] Building bubblewrap from sources

### ISSUE THREAD

**Issue by fruxo-** [containers/bubblewrap#363]
How can this package be built from its sources? I struggle to find instructions. I’ll be building it on an Amazon Linux 2 OS, which is a RedHat Linux derived distribution.

Thanks.

**Comment by TingPing** [comment]
Pretty standard stuff:

```
sudo yum-builddep bubblewrap
./autogen.sh
make
sudo make install
```

Was there a specific isssue?

**Comment by fruxo-** [comment]
Thanks. No, no issue regarding the build working or failing, just could not see any build instructions so I though asking.
