### ISSUE TITLE
bind /etc/hosts has no effect

### ISSUE THREAD

**Issue by uoee** [containers/bubblewrap#388]
I don't seem able to use the system hosts file in an expected way with

    --ro-bind /etc/hosts /etc/hosts

That is, I can normally block "example.com" with a line in `/etc/hosts`

    127.0.0.1 example.com

But such a hosts file has no blocking effect inside a bubblewrap container, even though the `/etc/hosts` file is accessible and can be read as a normal file.

What might explain this? Is there another approach I should take?

As an example, I was following the suggestion for Firefox at https://wiki.archlinux.org/index.php/Bubblewrap#Firefox, and just adding an extra `--ro-bind /etc/hosts /etc/hosts` was unsuccessful.

**Comment by alexlarsson** [comment]
A bubblewrap container can be anything. Whether it cares about `/etc/hosts` or not is completely up to the code that runs in the container. For the specific case of firefox it depends on the details for the firefox dns resolver.

**Comment by Maryse47** [comment]
IIRC for respecting `/etc/hosts` `/etc/nsswitch.conf` must exist too. Flatpak had this issue some time ago: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/345

**Comment by uoee** [comment]
Thank you both for the information.

For the specific case of Firefox the solution is indeed to add

    --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf
