### ISSUE TITLE
Does This lib support or will support windows and | or macos

### ISSUE THREAD

**Issue by litch0** [containers/bubblewrap#393]

**Comment by smcv** [comment]
No, bubblewrap does not support Windows and macOS. It also doesn't support non-Linux Unix systems such as BSD, Solaris and Hurd, and probably never will.

bubblewrap is Linux-specific: it makes use of [namespaces(7)](https://manpages.debian.org/unstable/manpages/namespaces.7.en.html), which are a Linux-specific kernel feature.
