### ISSUE TITLE
Feature Request: add zsh completion

### ISSUE THREAD

**Issue by CoelacanthusHex** [containers/bubblewrap#398]
As Bash Completion

**Comment by haraldkubota** [comment]
Since I created one for firejail and I got in the correct mood (and I'd like to learn more about zsh completion)...working on it!
See https://github.com/haraldkubota/bubblewrap/tree/zsh_completion/completions/zsh for the impatient.

**Comment by rusty-snake** [comment]
#410 is merged, this issue can be closed.
