### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by rhatdan** [containers/bubblewrap#422]

**Comment by rhatdan** [comment]
@alexlarsson @cgwalters PTAL

**Comment by smcv** [comment]
`flatpak/flatpak` and `flatpak/flatpak-builder` have just done the same rename. @alexlarsson, @cgwalters, any objection to applying it here too?

@nanonyme points out on Matrix that every time we rename branches, it's disruptive to downstream projects that consume whatever we are calling our development branch, so it's better to batch the disruption together into something that downstream projects can deal with in one transaction.

**Comment by cgwalters** [comment]
SGTM

**Comment by smcv** [comment]
Sorry, I thought I had the access level to do this myself, but it looks like I don't.

**Comment by cgwalters** [comment]
I flipped your role to Admin, did that work?

**Comment by smcv** [comment]
Branch renamed.
