### ISSUE TITLE
[Question] How can I enable access to /dev/tty to neovim inside bubblewrap?

### ISSUE THREAD

**Issue by nawordar** [containers/bubblewrap#423]
In order to have two different neovim versions with two different configs side-by-side, I decided to use bubblewrap. Using bubblewrap, I was able to create the following script, which mounts `~/.config/nvim-nightly` on top of `~/.config/nvim`:

```shell
#!/usr/bin/env sh

nvim_stable_config="$XDG_CONFIG_HOME/nvim"
nvim_stable_data="$XDG_DATA_HOME/nvim"

nvim_nightly_path="$HOME/clones/neovim"
nvim_nightly_runtime="$nvim_nightly_path/runtime"
nvim_nightly_config="$XDG_CONFIG_HOME/nvim-nightly"
nvim_nightly_data="$XDG_DATA_HOME/nvim-nightly"

nvim="$nvim_nightly_path/build/bin/nvim"

export VIMRUNTIME="$nvim_nightly_runtime"

bwrap                                                 \
  --bind  / /                                         \
  --dev   /dev                                        \
  --bind "$nvim_nightly_config" "$nvim_stable_config" \
  --bind "$nvim_nightly_data"   "$nvim_stable_data"   \
  "$nvim" "$@"
```

It works pretty well, but I cannot run commands which require access to `/dev/tty`. In particular, I would like to be able to run command `chezmoi apply`, to apply my dotfiles without exiting neovim. Instead, this command fails with the following message:

```
:!chezmoi apply
chezmoi: open /dev/tty: no such device or address

shell returned 1

Press ENTER or type command to continue
```

Is it possible to give access to `/dev/tty` to neovim inside bubblewrap?

**Comment by smcv** [comment]
`--dev /dev` creates a very minimal `/dev` with just enough to run a simple containerized app - it has `/dev/null` and `/dev/zero`, but not for example `/dev/sda` or `/dev/tty`.

If you are not trying to apply a meaningful security boundary, you probably want `--dev-bind /dev /dev` which exposes all possible device nodes in the container.

**Comment by smcv** [comment]
`--dev /dev` is at one extreme: it's the least `/dev` you can have and still say with a straight face that the container looks like Linux.

`--dev-bind /dev /dev` is the opposite extreme: it's all of `/dev` from the host.

More complex users of bubblewrap, like Flatpak, start from `--dev /dev` and then add individual device nodes or directories for other things that this particular app wants to use; for example a game with accelerated graphics might need `--dev /dev --dev-bind /dev/dri /dev/dri`.

**Comment by nawordar** [comment]
I tried `--dev-bind /dev /dev`, but I have the same error. Which is weird, because neovim should have an unrestricted access to `/dev`, including `/dev/tty`, right?

When I run `stat /dev/tty` inside neovim, it gives me this result:

```
:!stat /dev/tty
  File: /dev/tty
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 5h/5d   Inode: 11          Links: 1     Device type: 5,0
Access: (0666/crw-rw-rw-)  Uid: (65534/  nobody)   Gid: (65534/  nobody)
Access: 2021-05-21 19:10:37.819584352 +0200
Modify: 2021-05-21 19:10:37.819584352 +0200
Change: 2021-05-21 19:10:37.819584352 +0200
 Birth: -
```

Maybe permissions are the problem? Is it possible to mount as a different group?

**Comment by nawordar** [comment]
Never mind. I ran chezmoi with `--no-tty`, but it still doesn't work, because of other issue. Chezmoi shows that error message inside containerized neovim, because it tries to apply Neovim stable config to Neovim nightly config and tries to ask me, how to resolve conflicts.
