### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by smcv** [containers/bubblewrap#442]
I'd like to have a new bubblewrap release that Flatpak can depend on. Given the new features and the time since the last release, in the spirit of semantic versioning I think we should maybe go to 0.5.0 rather than 0.4.2.

I'd like to also land at least #439 and #440, fixing issues that I discovered while packaging a prerelease, before releasing this. I've uploaded 0cc286e + #439 + #440 to Debian experimental as 0.4.1+git20210624-1 to get it a bit more testing.

WIP release notes at https://github.com/containers/bubblewrap/releases/tag/untagged-41565790814eb650e9c6 (link will only work for maintainers).

**Comment by cgwalters** [comment]
Release notes LGTM.  Thanks for all of your work!

**Comment by smcv** [comment]
To be clear, is your intention that I do a release myself? I've never done that for this project.

Does https://github.com/flatpak/flatpak/blob/master/doc/release-checklist.md look suitable? (except for the bit about `NEWS` since this project doesn't have one, and `po/` since this project is not localized)

**Comment by alexlarsson** [comment]
@smcv I'm fine with you doing the release, and yeah, that checklist is about what I normally do for releases. We don't have a mailing list to mail to though.

**Comment by smcv** [comment]
0.5.0 released, smoke-tested, uploaded to Debian.
