### ISSUE TITLE
Question: will uninitialized memory contain data set from outside the sandbox?

### ISSUE THREAD

**Issue by ljwagerfield** [containers/bubblewrap#451]
Forgive my naivety, but is it possible for a process launched with `bwrap` to allocate memory that was previously-used by processes outside of the sandbox, not initialize it, and thus read the contents of variables set by other processes outside of the sandbox?

**Comment by smcv** [comment]
I don't think that's possible, but if it happens, there is nothing that bwrap could do differently to defend against it.

If it was possible for that to happen, then it would apply equally to anything else that crosses a namespace boundary (such as Docker, Podman, lxc), so I think it would be considered to be a security vulnerability in the Linux kernel.
