### ISSUE TITLE
how to bind to privileged port?

### ISSUE THREAD

**Issue by stef** [containers/bubblewrap#460]
excuse my ignorance, i spent quite some time using search engines and i could not find an answer. is it somehow possible to wrap a program that binds to a privileged port? i tried setcaping the program, i tried suiding it, i tried `--cap-add cap_net_bind_service` and my failure to grok this makes me feel very uncomfortable. pls enlighten me, and possibly others struggling with such simple issue..

**Comment by malte-v** [comment]
I'm running into the same issue right now. It's pretty easy to reproduce:
```
bwrap --unshare-all --share-net --cap-add cap_net_bind_service --ro-bind /usr /usr --ro-bind /lib /lib -- nc -l 20
```
Needless to say, I'm running `bwrap` as root.

**Comment by malte-v** [comment]
I think the problem is that `--cap-add` grants capabilities in the new user namespace, rather than the parent user namespace. That makes it pretty useless in conjunction with `--unshare-user`. See `man 7 user_namespaces`.

**Comment by stef** [comment]
my workaround was to just do a `sysctl net.ipv4.ip_unprivileged_port_start=442` and thus i can bind to port 443 from inside the bubblewrap.

**Comment by stef** [comment]
anyway, this:

> bubblewrap will not give you the ability to bind privileged ports if you could not already bind privileged ports outside its container. If it did, that would be a security vulnerability (privilege escalation).

is obviously true since the binary had `net_bind_service`  as a capability.

**Comment by malte-v** [comment]
> my workaround was to just do a sysctl net.ipv4.ip_unprivileged_port_start=442

Yep, that's what I do too. I don't think Linux supports granting parent user namespace capabilities to a child user namespace (at least I read nothing about it in the man page), so probably bubblewrap can't do much here.
