### ISSUE TITLE
Q: Will this protect me from the hundreds of GitHub binaries I add to my /usr/local/src?

### ISSUE THREAD

**Issue by ProfessorManhattan** [containers/bubblewrap#463]
I download hundreds of GitHub binaries because I think they're cool. I'm at the point where I know at least one of them has to include some sort of malware. Can I use this to prevent the binaries from getting access to stuff? Is there a better solution?

Thanks. Seems like a cool project.

**Comment by smcv** [comment]
> I download hundreds of GitHub binaries because I think they're cool. I'm at the point where I know at least one of them has to include some sort of malware.

I would recommend applying some critical thinking to what you're willing to run and trust, either doing your own review or delegating it to a community project that you trust (like a Linux distribution).

> Can I use this to prevent the binaries from getting access to stuff?

Maybe? bubblewrap is a tool to restrict what programs can do (it's mechanism, not policy). It can apply restrictions to processes, but it cannot create a security policy out of nothing: the security policy needs to come from you, or from some larger framework. Designing a security policy that gives programs enough access to be useful, but not enough access to do damage, is not straightforward.

If what you are looking for is a complete app framework, you will need to either use something like Flatpak (which uses bubblewrap) or Snap (which doesn't), or build your own.

If you look at what Flatpak does, you will realise that bubblewrap is an important part of the overall design, but there's a lot of other security-sensitive infrastructure outside bubblewrap's scope.

**Comment by ProfessorManhattan** [comment]
Hey @smcv -- thanks so much for the detailed explanation. I'm still trying to figure out how far to go for "due diligence" in terms of security for project dependencies. Nearly every project I work with references some new NPM package, GitHub binary, or other miscellaneous dependency.. NPM packages (some binary based) don't even force the release on npmjs.com to match the source code linked to in the GitHub link.

It would be interesting to see some method of automatically estimating the least permissive, functional configuration for generating bubblewrapped binaries. I know Docker-Slim allows you to specify an executable name and automatically includes dependent libs and generates AppArmor profiles.
