### ISSUE TITLE
How to inherit the suid of root?

### ISSUE THREAD

**Issue by Neutron3529** [containers/bubblewrap#490]
I checked the ArchWiki, found something like
> No-op
> A no-op bubblewrap invocation is as follows:
> $ bwrap --dev-bind / / bash
It seems that this operation is not no-op, since bubblewrap change the ownership from root:root to nobody:nobody
I'm now jail my steam in the bubblewrap, and I fine-tuned my GPU by a program (which decrease the clock rate to make my GPU cooler), which set suid.
the command of steam looks like:
```
my-custom-command %command% # main process will keep alive until its fork is dead, while its fork discard all the permissions and execute the original steam command.
```
which works fine before jail my steam into bubblewrap. After that, `my-custom-command`'s owner changed to nobody:nobody, thus cannot communicate with nvidia-smi, thus cannot change the clock rate.

Is there any suggestions for such suid programs?

**Comment by rusty-snake** [comment]
> I checked the ArchWiki, found something like
>
> > ### No-op
> > A no-op bubblewrap invocation is as follows:
> >
> >     $ bwrap --dev-bind / / bash
>
> It seems that this operation is not no-op, since bubblewrap change the ownership from root:root to nobody:nobody

If you continue reading in the Arch wiki you will find

> **Note:** This operation will modify all the owner and group to `nobody` if the owner or group is not the current one, which suggests running some program like `sudo` will not work properly.

And the short answer is that you can not run suid programs inside bubblewrap.

> bubblewrap uses `PR_SET_NO_NEW_PRIVS` to turn off setuid binaries

**Comment by Neutron3529** [comment]
> If you continue reading in the Arch wiki you will find

cur[prev](https://wiki.archlinux.org/index.php?title=Bubblewrap&diff=725090&oldid=720930) [15:43, 2 April 2022](https://wiki.archlinux.org/index.php?title=Bubblewrap&oldid=725090)‎ [Neutron3529](https://wiki.archlinux.org/index.php?title=User:Neutron3529&action=edit&redlink=1) [talk](https://wiki.archlinux.org/index.php?title=User_talk:Neutron3529&action=edit&redlink=1) [contribs](https://wiki.archlinux.org/title/Special:Contributions/Neutron3529)‎ m 26,498 bytes +215‎ Clearify that the no-op bubblewrap is actually doing something. [undo](https://wiki.archlinux.org/index.php?title=Bubblewrap&action=edit&undoafter=720930&undo=725090)

Actually that line is edit just before my issue, and was edited by myself.

> And the short answer is that you can not run suid programs inside bubblewrap.

Thanks for your remind. But I find it might be convenient to expose some suid program to bubblewrap.
Is there, or will there be some additional option to enable some suid flag?

**Comment by rusty-snake** [comment]
> Is there, or will there be some additional option to enable some suid flag?

<sub><sup>I'm not speaking for the bubblewrap authors</sup></sub> &nbsp; &nbsp; No
At least for suid installed bubblewrap this can not be done securely.

**Comment by smcv** [comment]
@rusty-snake is correct. If we didn't use `PR_SET_NO_NEW_PRIVS`, then it would be trivial to do something like this:

```
$ echo 'ALL=(ALL:ALL) NOPASSWD: ALL' > give-everyone-root
$ chmod 0440 give-everyone-root
$ bwrap --dev-bind / / --bind give-everyone-root /etc/sudoers -- sudo touch /pwned
```

(Obviously an actually malicious attacker would do something more destructive than `touch /pwned` as their attack payload.)

**Comment by Neutron3529** [comment]
> @rusty-snake is correct. If we didn't use `PR_SET_NO_NEW_PRIVS`, then it would be trivial to do something like this:
> 
> ```
> $ echo 'ALL=(ALL:ALL) NOPASSWD: ALL' > give-everyone-root
> $ chmod 0440 give-everyone-root
> $ bwrap --dev-bind / / --bind give-everyone-root /etc/sudoers -- sudo touch /pwned
> ```
> 
> (Obviously an actually malicious attacker would do something more destructive than `touch /pwned` as their attack payload.)

well.

I found some strange thing:
```
sudo bwrap --cap-add CAP_SYS_ADMIN --dev-bind / / sudo -u $USER /bin/bash -c "echo second sudo works fine but the third failed;sudo echo success"
```
If we use root access, add the `CAP_SYS_ADMIN` privileges, then we could use sudo as root, but if we switch to a user, the sudo failed to execute.

If we have root access, and we could perform sudo in bwrap, why we can't grant suid to a specific program?

**Comment by rusty-snake** [comment]
> If we have root access, and we could perform sudo in bwrap, why we can't grant suid to a specific program?

NNP (`PR_SET_NO_NEW_PRIVS`) is not selective for a specific program.

I don't think it is feasible to implement suid-deny-default-allow-exceptionally with namespaces and even if it is possible we can not give the user control of this feature.

> If we use root access, add the CAP_SYS_ADMIN privileges, then we could use sudo as root, but if we switch to a user, the sudo failed to execute.

`sudo` needs to be root either by starting it as root or by suid. If you start bubblewrap as root (and keep some caps) sudo can work because it does not need suid to become root.
