### ISSUE TITLE
Command-line arguments being displayed in the command of the minimal pid 1 process in the sandbox might be undesirable

### ISSUE THREAD

**Issue by AtticFinder65536** [containers/bubblewrap#503]
If you use `--unshare-pid` without `--as-pid-1`, there is an additional bwrap minimal pid 1 process. That process contains the full command-line arguments used in bubblewrap. One may not want that information to be accessible by processes in the sandbox. For example, `--bind /original/directory/on/host/cool-files /cool-files`: processes in the sandbox can see the original directory name on the host by looking at the name of the command used in the bwrap minimal pid 1 process. That might not be desirable in some scenarios. I'm not sure how easy it would be to change that minimal pid 1 process to just show `bwrap`.

**Comment by smcv** [comment]
If you want to avoid leaking information to other processes, editing the `argv` from application code is already too late: someone might have retrieved the `argv` from `ps` before you had the opportunity to edit it.

A better way to hide information from other processes is to write the potentially sensitive arguments into the write end of a pipe, let the bwrap process inherit the read end of the pipe, and pass its file descriptor number as the argument to `--args`. This is [what Flatpak does](https://github.com/flatpak/flatpak/blob/1.13.2/common/flatpak-bwrap.c#L346), partly to hide potentially sensitive arguments and environment variables from other users, but also partly to avoid hitting arbitrary limits on command-line length if it needs to pass a lot of arguments to bwrap.

**Comment by smcv** [comment]
For example, with a Flatpak app running:

```
pgrep bwrap|xargs ps
    PID TTY      STAT   TIME COMMAND
  59919 pts/0    S+     0:00 bwrap --args 41 portal-test-gtk3
  59929 pts/0    S+     0:00 bwrap --args 41 xdg-dbus-proxy --args=43
  59933 pts/0    S+     0:00 bwrap --args 41 portal-test-gtk3
```

There's nothing special about Flatpak here, any other user of bwrap can do the same.
