### ISSUE TITLE
Unshare abstract network namespace but share inet

### ISSUE THREAD

**Issue by WhyNotHugo** [containers/bubblewrap#504]
I'd like to restrict a sandbox from accessing any abstract unix domain sockets on the host, but allow outgoing internet connections.

It seems `--unshare-net` and `--share-net` are very black and white, and there's no middle-ground.

Is it possible to do what I'm trying to do with bubblewrap?

**Comment by WhyNotHugo** [comment]
Oh, I think I missed #330 when searching.

**Comment by WhyNotHugo** [comment]
Looks like #392 is what I want.

**Comment by rusty-snake** [comment]
> Is it possible to do what I'm trying to do with bubblewrap?

Is this possible with Linux? No.

But you can integrate slirp4netns (#392). Minimal example (stolen from `slirp4netns(1)`):

```
term-1$ bwrap --dev-bind / / --unshare-net bash
term-1$ echo $$ > /tmp/pid
term-2$ slirp4netns --configure --mtu=65520 $(cat /tmp/pid) tap0
term-1$ /usr/bin/wget 1.1.1.1
```

**Comment by WhyNotHugo** [comment]
Oh, that's pretty neat, thanks!

> Is this possible with Linux? No.

So, given that Flatpak uses this (but doesn't seem to use slirp4netns), doesn't that imply that any application with network access can access abstract unix sockets on the host?

**Comment by WhyNotHugo** [comment]
Thanks for that example, it's brilliant!

I think that kind covers #392, right? I mean, things like `xdg-dbus-proxy` aren't built-in, so I don't expect this would be either.

**Comment by rusty-snake** [comment]
> So, given that Flatpak uses this (but doesn't seem to use slirp4netns), doesn't that imply that any application with network access can access abstract unix sockets on the host?

Yes.

**Comment by rusty-snake** [comment]
> Thanks for that example, it's brilliant!

If you want an more advanced example: https://codeberg.org/crabjail/crabjail/src/commit/bb8ab40f9538fe3b4436eb32249be0ed2d66a599/src/crabjail.rs#L698
