### ISSUE TITLE
Question about wayland config

### ISSUE THREAD

**Issue by BirdInFire** [containers/bubblewrap#507]
Hello 
i actually use for one software (who work on X11 but support wayland (so it startup xwayland even if it can work on wayland), so i want to do like firejail --x11=none, is it possible with bubblewrap (if yes how)

i ask because on firejail i have to create a net config to get rid of "abstract X11 listener" error.

Since i also use brave on Fedora, i will also use bubblewrap if it's possible to restrict X (to prevent Xwayland launch).

Thanks !

**Comment by Kron4ek** [comment]
Hello,

All X applications rely on the DISPLAY environment variable to connect to the X server. So simply unsetting this variable should do the trick. It is not a completely strict way, apps can still set DISPLAY for themselfs even if you unset it, but it should work in most cases. For example:

```
bwrap --bind / / --dev-bind /dev /dev --proc /proc --unsetenv DISPLAY application_binary
```

If you need a more stricter way to restrict acess to X, you can disable access to the directory with X sockets (`/tmp/.X11-unix` by default on most distros) and make Xorg not to listen on abstract sockets.

**Comment by BirdInFire** [comment]
> Hello,
> 
> All X applications rely on the DISPLAY environment variable to connect to the X server. So simply unsetting this variable should do the trick. It is not a completely strict way, apps can still set DISPLAY for themself even if you unset it, but it should work in most cases. For example:
> 
> ```
> bwrap --bind / / --dev-bind /dev /dev --proc /proc --unsetenv DISPLAY application_binary
> ```
> 
> I tested the way with unsetting DISPLAY on sway and it definitely prevents applications from using Xwayland.
> 
> If you need a more stricter way to forbid access to X, you can remove access to the directory with the X sockets (`/tmp/.X11-unix` by default on most distros) and make Xorg (xwayland) not to listen on abstract sockets.

I will try thanks for the answer, it's a shame that wayland do not have a env settings to prevent xwayland to start (now that majority of big software have a functionnal native wayland version).

**Comment by rusty-snake** [comment]
> it's a shame that wayland do not have a env settings to prevent xwayland to start

That's not a wayland thing. It's a implementation thing (i.e. it depends on the wayland compositor).

> you can remove access to the directory with the X sockets (/tmp/.X11-unix by default on most distros)

bubblewrap: `--tmpfs /tmp/.X11-unix`

**Comment by BirdInFire** [comment]
i have one question (will post my final config line here), i have this one error (it launch but the app is blurry) how can i fix it : libEGL warning: wayland-egl: drmGetMagic failed, i do thinks it's a binding i have forgotten, and the app cannot access it.

**Comment by rusty-snake** [comment]
If you don't post your config helping is much harder.
General: Which /dev and /sys and /etc bind do you have?

**Comment by BirdInFire** [comment]
This is the version i work on who cause the bug (i have changed my username by USERNAME et the app folder by APP,
I do try to maintain it without autorize to much in one line like that i can copy past in for various of app).

Thanks for any help

bwrap \
--symlink usr/lib /lib \
--symlink usr/lib64 /lib64 \
--symlink usr/bin /bin \
--symlink usr/bin /sbin \
--ro-bind /usr/lib /usr/lib \
--ro-bind /usr/lib64 /usr/lib64 \
--ro-bind /usr/bin /usr/bin \
--ro-bind /usr/share/applications /usr/share/applications \
--ro-bind /usr/share/gtk-3.0 /usr/share/gtk-3.0 \
--ro-bind /usr/share/gtk-4.0 /usr/share/gtk-4.0 \
--ro-bind /usr/share/fontconfig /usr/share/fontconfig \
--ro-bind /usr/share/drirc.d /usr/share/drirc.d \
--ro-bind /usr/share/fonts /usr/share/fonts \
--ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
--ro-bind /usr/share/glvnd /usr/share/glvnd \
--ro-bind /usr/share/icons /usr/share/icons \
--ro-bind /usr/share/libdrm /usr/share/libdrm \
--ro-bind /usr/share/mime /usr/share/mime \
--ro-bind /usr/share/icons /usr/share/icons \
--ro-bind /usr/share/mime /usr/share/mime \
--ro-bind /etc/fonts /etc/fonts \
--ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
--dir /run/user/"$(id -u)" \
--ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse \
--ro-bind "/run/user/$(id -u)/pipewire-0" "/run/user/$(id -u)/pipewire-0" \
--ro-bind /run/user/"$(id -u)"/wayland-0 /run/user/"$(id -u)"/wayland-0 \
--dev /dev \
--dev-bind /dev/dri /dev/dri \
--ro-bind /sys/dev/char /sys/dev/char \
--proc /proc \
--tmpfs /tmp \
--bind /home/USERNAME/APP /home/USERNAME/APP \
--bind /opt/APP /opt/APP \
--setenv HOME /home/USERNAME \
--setenv PATH /usr/bin \
--hostname RESTRICTED \
--unshare-all \
--die-with-parent \
--new-session \
--tmpfs /tmp/.X11-unix \
/opt/APP/bin

**Comment by BirdInFire** [comment]
Note : not having internet connection is wanted not a forgotten line ^^

**Comment by rusty-snake** [comment]
Please use codeblocks for this, it is an unreadable mess.

- Does if work with `--bind /sys /sys --dev-bind /dev /dev`?
- Does it work with `--dev-bind /dev/$nvidia /dev/$nvidia` for all `/dev/nvidia*`?

>  --tmpfs /tmp

FYI: You can use `--dir /tmp`

>  --tmpfs /tmp/.X11-unix 

If you do not share `/tmp` this is redundant (unless you want this mountpoint).

**Comment by BirdInFire** [comment]
> * --dev-bind /dev/$nvidia /dev/$nvidia

it does work but start as xwayland (and it's why i do try to prevent with bwrap (it do work on wayland with firejail, so here i so try to replicate with bubblewrap to remove firejail))

**Comment by rusty-snake** [comment]
But this app supports wayland without being blurry in general? i.e. `bwrap --dev-bind / / --tmpfs /dev/nvidi... --tmpfs /tmp/.X11-unix ... --unshare-all` works.
So it's really only about an missing bind and not a but in the app.

**Comment by BirdInFire** [comment]
> But this app supports wayland without being blurry in general? i.e. `bwrap --dev-bind / / --tmpfs /dev/nvidi... --tmpfs /tmp/.X11-unix ... --unshare-all` works. So it's really only about an missing bind and not a but in the app.

i have (by conscience tried to restart my DE) and the blur have disapeared, will go on the DE git if i can replicate this if not isolated bug, thanks for the help and i post the final version here before closing 

thanks @rusty-snake  

bwrap \
--symlink usr/lib /lib \
--symlink usr/lib64 /lib64 \
--symlink usr/bin /bin \
--symlink usr/bin /sbin \
--ro-bind /usr/lib /usr/lib \
--ro-bind /usr/lib64 /usr/lib64 \
--ro-bind /usr/bin /usr/bin \
--ro-bind /usr/share/applications /usr/share/applications \
--ro-bind /usr/share/gtk-3.0 /usr/share/gtk-3.0 \
--ro-bind /usr/share/gtk-4.0 /usr/share/gtk-4.0 \
--ro-bind /usr/share/fontconfig /usr/share/fontconfig \
--ro-bind /usr/share/drirc.d /usr/share/drirc.d \
--ro-bind /usr/share/fonts /usr/share/fonts \
--ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
--ro-bind /usr/share/glvnd /usr/share/glvnd \
--ro-bind /usr/share/icons /usr/share/icons \
--ro-bind /usr/share/libdrm /usr/share/libdrm \
--ro-bind /usr/share/mime /usr/share/mime \
--ro-bind /usr/share/icons /usr/share/icons \
--ro-bind /usr/share/mime /usr/share/mime \
--ro-bind /etc/fonts /etc/fonts \
--ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
--dir /run/user/"$(id -u)" \
--ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse \
--ro-bind "/run/user/$(id -u)/pipewire-0" "/run/user/$(id -u)/pipewire-0" \
--ro-bind /run/user/"$(id -u)"/wayland-0 /run/user/"$(id -u)"/wayland-0 \
--dev /dev \
--dev-bind /dev/dri /dev/dri \
--ro-bind /sys/dev/char /sys/dev/char \
--proc /proc \
--dir /tmp \
--bind /home/USERNAME/APP /home/USERNAME/APP \
--bind /opt/APP /opt/APP \
--setenv HOME /home/USERNAME \
--setenv PATH /usr/bin \
--hostname RESTRICTED \
--unshare-all \
--die-with-parent \
--new-session \
/opt/APP
