### ISSUE TITLE
Fake cpuinfo

### ISSUE THREAD

**Issue by mvasi90** [containers/bubblewrap#513]
Hello everyone.

After mounting the `/proc` filesystem with the flag `--proc /proc `, is impossible to bind the `/proc/cpuinfo`: `bwrap: Can't create file /proc/cpuinfo: Permission denied`.

How can I bind a fake cpuinfo?

**Comment by rusty-snake** [comment]
WFM (Fedora 35)

```console
$ touch cpuinfo
$ alias bwrap-sys="bwrap --ro-bind /etc /etc --ro-bind /usr /usr --symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/sbin /sbin --dir /tmp --dev-bind /dev /dev --bind /proc /proc --ro-bind /sys /sys --ro-bind /var /var --ro-bind /run /run --bind $XDG_RUNTIME_DIR $XDG_RUNTIME_DIR --dir $HOME"
$ bwrap-sys --bind ./cpuinfo /proc/cpuinfo cat /proc/cpuinfo
$ bwrap-sys --unshare-pid --bind ./cpuinfo /proc/cpuinfo cat /proc/cpuinfo
$ bwrap --version
bubblewrap 0.5.0
```

Can you give some more details to reproduce (e.g. Distribution, Bubblewrap version, command line you tried).

**Comment by mvasi90** [comment]
Distribution: Gentoo Linux
BubbleWrap: 0.5.0

You are binding the full host /proc filesystem with read-write permissiong with the flag `--bind /proc /proc`.
Please try it with the `--proc /proc` flag.

**Comment by rusty-snake** [comment]
WFM (Fedora 35)

```console
$ touch cpuinfo
$ alias bwrap-sys="bwrap --ro-bind /etc /etc --ro-bind /usr /usr --symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/sbin /sbin --dir /tmp --dev-bind /dev /dev --proc /proc --ro-bind /sys /sys --ro-bind /var /var --ro-bind /run /run --bind $XDG_RUNTIME_DIR $XDG_RUNTIME_DIR --dir $HOME"      
$ bwrap-sys --bind ./cpuinfo /proc/cpuinfo cat /proc/cpuinfo
$ bwrap-sys --unshare-pid --bind ./cpuinfo /proc/cpuinfo cat /proc/cpuinfo
$ bwrap --version
bubblewrap 0.5.0
```

Can you give some more details to reproduce (e.g. Distribution, Bubblewrap version, command line you tried).

**Comment by mvasi90** [comment]
Distribution: Gentoo Linux
BubbleWrap: 0.5.0

You are binding the full host /proc filesystem with read-write permissiong with the flag `--bind /proc /proc`.
Please try it with the `--proc /proc` flag.

**Comment by mvasi90** [comment]
> Anyway WFM with `--proc /proc` too (see updated comment above).

For me, your example doesn't work at all.

```bash
$ alias bwrap-sys="bwrap --ro-bind /etc /etc --ro-bind /usr /usr --symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/sbin /sbin --dir /tmp --dev-bind /dev /dev --proc /proc --ro-bind /sys /sys --ro-bind /var /var --ro-bind /run /run --bind $XDG_RUNTIME_DIR $XDG_RUNTIME_DIR --dir $HOME"

$ bwrap-sys --bind ./cpuinfo /proc/cpuinfo cat /proc/cpuinfo
bwrap: execvp cat: No such file or directory

$ bwrap-sys --unshare-pid --bind ./cpuinfo /proc/cpuinfo cat /proc/cpuinfo
bwrap: execvp cat: No such file or directory
```
It works changed to:
```bash
alias bwrap-sys="bwrap --ro-bind /etc /etc --ro-bind /usr /usr --ro-bind /bin /bin --ro-bind /lib /lib --ro-bind /usr/lib /usr/lib --ro-bind /lib64 /lib64 --ro-bind /usr/lib64 /usr/lib64 --dir /tmp --dev-bind /dev /dev --proc /proc --ro-bind /sys /sys --ro-bind /var /var --ro-bind /run /run --bind $XDG_RUNTIME_DIR $XDG_RUNTIME_DIR --dir $HOME"
```

But I need to do it at fly, using filedescriptors instead files:
```bash
bwrap-sys 18< <(echo test) --file 18 /proc/cpuinfo cat /proc/cpuinfo
bwrap: Can't create file /proc/cpuinfo: Permission denied
```

**Comment by mvasi90** [comment]
Solved.
It works replacing the flag `--file 18 /proc/cpuinfo` by `--bind-data 18 /proc/cpuinfo`

Thank you for you time.

**Comment by rusty-snake** [comment]
The reason is that `--file` does not bind, it "[copies] from the file descriptor FD to DEST."

**Comment by mvasi90** [comment]
> The reason is that `--file` does not bind, it "[copies] from the file descriptor FD to DEST."

Yes, you are right. I missed that.
Thank you!
