### ISSUE TITLE
Replacing a system call instead of returning an error

### ISSUE THREAD

**Issue by mvasi90** [containers/bubblewrap#514]
Hello everyone.
I think this is not the right place to ask these questions, but I try.

**Details**
I want to replace the `utsname` structure of the `uname` syscall, instead of blocking it and returning an error with the `seccomp` filter.

**Motivation**
The sandbox enviroment protects your privacy and improve the security of your system . For now, the container tools (lxc, docker, etc.) and the sandboxing tools (firejail, bwrap, minijail, etc.) protects your personal files and some system information, but no one protects you against fingerprinting.

I'm working on a script that creates bwrap profiles in seconds, that only uses needed files/folders, environment variables, libraries and syscalls.
The script also modifies the kernel information like:
- /proc/version
- /proc/sys/kernel/os{release,type}
- /etc/hosts
- /etc/hostname
- /usr/bin/uname (fake kernel and system info)
- /proc/cpuinfo (fake processor)
- etc.

But the `uname` syscall returns the real kernel information.
How can I intercept a syscall and return different values at runtime without using `gdb`, `strace` or `LD_PRELOAD`. The `seccomp` filter can do that?

**Comment by rusty-snake** [comment]
> but no one protects you against fingerprinting.
>
> I'm working on a script that creates bwrap profiles in seconds, that only uses needed files/folders, environment variables, libraries and syscalls

OT: This is likely impossible. Especially if you want to use things like PulseAudio for example which requires `/etc/machine-id`.

**Comment by rusty-snake** [comment]
> How can I intercept a syscall and return different values at runtime without using `gdb`, `strace` or `LD_PRELOAD`. The seccomp filter can do that?

`LD_PRELOAD` can not intercept a syscall, you can still call it directly i.e. `syscall(SYS_foo, ...)`. I hope you know that, otherwise it could be dangerous to write a sandbox if you lack the technical knowledge of the technologies behind it.

**Comment by rusty-snake** [comment]
Do you run `pulseaudio` or `pipewire-pulse`?

It was an example, there are hundreds more I guess.

**Comment by mvasi90** [comment]
> `LD_PRELOAD` can not intercept a syscall, you can still call it directly i.e. `syscall(SYS_foo, ...)`. I hope you know that, otherwise it could be dangerous to write a sandbox if you lack the technical knowledge of the technologies behind it.

Of course, that's why I specified "without gdb/strace and LD_PRELOAD".

**Comment by mvasi90** [comment]
> Do you run `pulseaudio` or `pipewire-pulse`?

`pulseaudio`

**Comment by rusty-snake** [comment]
> Of course, that's why I specified "without gdb/strace and LD_PRELOAD".

Since I'm not sure if this is an acceptable solution or not, I write it.

Applications rarely invoke syscalls directly, the almost always use the glibc wrapper. You can use seccomp-bpf to block the syscall and LD_PRELOAD to preload a wrapper which fakes the values for applications.

**Comment by mvasi90** [comment]
> There are two exceptions to the to what I have just said. The one being `SECCOMP_RET_TRACE` which allows various manipulations. However this involves ptrace which means it's electively gdb/strace. The other one are user-space notifications (`seccomp_unotify(2)`) which can dereference pointers and fake the syscall **return value**. They can not safely write into the memory of the sandboxed process.

With that, I guess the issue could be closed.
I would try blocking the `uname` system call, hoping there are no applications that depend on it to work.

**Comment by rusty-snake** [comment]
> pulseaudio

Maybe something has changed recently or you have a special configuration. Anyway I know a lot systems where this isn't the case. And as I said, it was an example.

**Comment by mvasi90** [comment]
> Applications rarely invoke syscalls directly, the almost always use the glibc wrapper. You can use seccomp-bpf to block the syscall and LD_PRELOAD to preload a wrapper which fakes the values for applications.

Okay. I will try it.
Thank you very much.

**Comment by rusty-snake** [comment]
> /proc/cpuinfo (fake processor)

FYI: https://en.wikipedia.org/wiki/CPUID

**Comment by mvasi90** [comment]
> > /proc/cpuinfo (fake processor)
> 
> FYI: https://en.wikipedia.org/wiki/CPUID

Depends on the software. For example, using a similar processor with the same architecture, works well: firefox, signal messenger, AutoFirma (spanish government tool, and other government websites that downloads and executes java bytecode in jnlp -the deprectaed java web start-, putting your privacy and security at risk), etc.

**Comment by mvasi90** [comment]
> What has this todo with my comment? My comment was about querying cpu-information directly via processor-instructions.

From you link of Wikipedia:
> A program can use the CPUID to determine processor type and whether features such as MMX/SSE are implemented.

So I mentioned that for those simple applications that don't usually make use of processor-specific instructions, like some games that include assembly code, that's fine. Works well with a similar processor.

Since one thing leads to another, I mentioned my settings that improve the privacy and security of my devices and data. Many applications are collecting personal information: Android Studio, vim/nvim programming plugins, etc.
You can think that Signal private messenger is secure because has end ot end encryption. Yes it is but it uses Google libraries that are connected to Google servers all the time. There is no privacy.

They are related things but off-topic, so I will mark some comments as off-topic to improve the reader experience.
