### ISSUE TITLE
running setuid binaries from bwrap

### ISSUE THREAD

**Issue by haampie** [containers/bubblewrap#517]
Is there any chance setuid binaries could work inside of non-setuid bubblewrap? I'm trying to run a setuid binary that creates a new mount namespace, but fails. When I remove `MS_NOSUID` from the mount flags in bwrap, and remove the no_new_privs bit, it still doesn't work. Why is this?

**Comment by smcv** [comment]
The reason this doesn't work is that the kernel will only allow a non-setuid bubblewrap to create containers where it won't work.

The reason the kernel will only allow that is that otherwise, there'd be a security vulnerability like the one I described.

**Comment by rusty-snake** [comment]
> Why is this?

Capabilities

Depending on you use-case `--cap-add` may works for you.

```console
$ LC_ALL=C bwrap --dev-bind / / --unshare-all unshare -m
unshare: unshare failed: Operation not permitted
$ LC_ALL=C bwrap --dev-bind / / --unshare-all --cap-add CAP_SYS_ADMIN unshare -m
[rusty-snake@localhost ~]$ 
```
