### ISSUE TITLE
Secondary Group Availability

### ISSUE THREAD

**Issue by schutzcw** [containers/bubblewrap#525]
I may be missing something fundamental about how bubblewrap works, in which case I apologize if this ends up being a question rather than an bug/issue.

My question in a brief sentence is: Why aren't secondary groups for a user propagated into the bubblewrap container? Below is an attempt to provide a minimal set of steps to describe what I mean:

Versioning:
Host: Ubuntu 18.04.4 LTS
Bwrap version: 0.2.1
*Please note that I've tested on Ubuntu 20.04 with Bwrap version 0.4.0 as well with the same results

1) Create a new group called 'test_group' on the host machine
`sudo groupadd test_group`
Note: I had to log out and log back in for this to take effect

2) Add my user 'str' to the new group 'test_group'
`sudo usermod -a -G test_group str`

3) Create a test file in the $HOME directory on the host machine and set the group to the new test_group
```
touch $HOME/test.txt
sudo chown str:test_group test.txt
```

4) Show permissions on host machine
```
ls -lh $HOME/test.txt
-rw-rw-r-- 1 str test_group 0 Aug 25 15:13 /home/str/test.txt
```
5) Run minimal bwrap. and check permissions in bwrap:
`bwrap --dev-bind / / bash`

6) Check permissions in bwrap container:
```
ls -lh $HOME
-rw-rw-r-- 1 str nogroup 0 Aug 25 15:13 /home/str/test.txt
```
My question is why is the test_group group shown as nogroup here? If I `cat /etc/group` inside the container, I see the following entry  `test_group:x:1004:str`, which to me means that the test_group should exist and shouldn't be displayed as nogroup.

Additionally, if I type `id` on the hostmachine, I see the primary group as well as secondary groups:
`uid=1000(str) gid=1000(str) groups=1000(str),24(cdrom),27(sudo),30(dip),1004(test_group)`

But, when I'm in the container, I just see the primary group and nogroup:
`uid=1000(str) gid=1000(str) groups=1000(str),65534(nogroup)`

Big thanks in advance for any help/insight on this!

**Comment by smcv** [comment]
> Why aren't secondary groups for a user propagated into the bubblewrap container?

Because the kernel won't allow it, see user_namespaces(7). Because we don't (usually) have `CAP_SETGID` in the parent namespace, "The data written to uid_map (gid_map) must consist of a single line  that maps the writing process's effective user ID (group ID) in the parent user namespace to a user ID  (group  ID)  in the user namespace." Mapping other groups is not allowed.
