### ISSUE TITLE
RFC: prefix syslog messages

### ISSUE THREAD

**Issue by toralf** [containers/bubblewrap#528]
I do run a dozen Gentoo linux build boxes, each in a bubblewrapped environment.
It would be cool to have syslog messages to /var/log/messages being prefixed if the process runs within such a bubble.

**Comment by smcv** [comment]
bubblewrap doesn't do anything special with syslog.

If you want to implement syslog filtering or prefixing, the way to do it would probably be something like this:

* write a server that listens on an AF_UNIX socket, implements the syslog protocol, filters or edits messages, and sends the filtered or edited messages to the real `/dev/log`
* in whatever script or higher-level framework you are using to launch bubblewrap environments, for each environment, run a copy of the server (perhaps something like `my-syslog-proxy --listen /run/syslog-proxies/buildbox-12 --output /dev/log` &)
* bind-mount the server's listening socket into the environment on top of the real `/dev/log` (perhaps something like `bwrap ... --dev /dev --ro-bind /run/syslog-proxies/buildbox-12 /dev/log ...`)
* if using systemd, either make sure the bubblewrap environments don't have access to `/run/systemd/journal`, or put a proxy in front of that too

Flatpak does something similar to put a filtering proxy (xdg-dbus-proxy) in front of the D-Bus session bus socket.

bwrap provides the necessary mechanism to do this, but actually implementing it is outside bwrap's scope.
