### ISSUE TITLE
Typo in --pidns help?

### ISSUE THREAD

**Issue by hadess** [containers/bubblewrap#531]
```
bubblewrap.c:           "    --pidns FD                   Use this user namespace (as parent namespace if using --unshare-pid)\n"
```

But `--unshare-pid` says:
```
bubblewrap.c:           "    --unshare-pid                Create new pid namespace\n"
```

The help should probably read `Use this pid namespace`.

**Comment by smcv** [comment]
At first I thought your issue report was suggesting that the `(as parent namespace...)` suffix is untrue and should be deleted. But actually I think the issue you're reporting is that it says `Use this user namespace`, where it should say `Use this pid namespace`?

If this had been a one-word PR (possibly created via Github's web UI without actually compiling anything), it would have been obvious what you meant, and I'd likely have merged it by now.

For the record, the suffix in parentheses is also true, with the four possible modes being:

1. `bwrap`: stay in the current pid namespace
2. `bwrap --unshare-pid`: unshare the pid namespace, creating a new pid namespace which is a child of the current one (Flatpak normally uses this)
3. `bwrap --pidns=5`: join the pid namespace provided via fd 5 (`flatpak-spawn --share-pids` uses this)
4. `bwrap --pidns=5 --unshare-pid`: first join the pid namespace provided via fd 5, and then unshare the pid namespace, creating a new pid namespace which is a child of the one that was provided (`flatpak-spawn --expose-pids` uses this)

**Comment by hadess** [comment]
I'll bear that in mind for next time. Thanks
