### ISSUE TITLE
How to create on disk instead of tmpfs!?

### ISSUE THREAD

**Issue by cayolblake** [containers/bubblewrap#532]
@rusty-snake is it possible to have bubblewrap create it's working image on disk instead of tmpfs?

The main target is primarily being able to `debug` the image being created, helpful in complex usages and also will ease creating multi version library instances of a container.

**Comment by rusty-snake** [comment]
The initial root will always be a tmpfs w/o modifying bubblewraps source code. However, you can start a mount over root like `bwrap --dev-bind /foo/bar / ...`.

IDK what or how you want to debug, but bubblewrap does not create a image like docker/buildah/podman do. It just does some mounts to setup a new filesystem tree. Those mounts will not be visible outside of bubblewrap. Speaking in docker terms, it's like an empty image with a lot of volumes.

**Comment by cayolblake** [comment]
Well, I used to depend on linux-user-chroot and debugging was so easy in terms of when a binary cannot find its libs or any other dependencies.

An example of not being able to debug problems properly, I am trying to create an environment where only the required libs exists (like I'm used to when creating with linux-user-chroot) so I don't mount bind /usr/lib or /usr/lib64 and instead tried to only bind the individually required libs and written some recursive detection code where it takes a binary and detects its deps libs, and the deps libs deps and so on to be able to detect the exact libs list needed inside, then I fire bwrap accordingly to find that `--ro-bind` does not follow symlinks 🤦  so I had to add another logic to walkthrough and resolve these and then create two lists, one to ro-bind and another to symlink.

After walking down this road and consuming so much time, still /bin/sh can't resolve one of the libs, so, I am left with no option to debug at all, which with `linux-user-chroot` would've been just examining the environment without chrooting to it and finding out where things got messed up.

Any advices on that? 🤔

**Comment by rusty-snake** [comment]
Where did you expected it to follow symlinks? Because it follows symlinks for me.

If you want to have a shell with some basic commands like `ls` inside bubblewrap, to list the filesystem tree, w/o having proper `/usr/lib{64,}`, a statically linked busybox binary is the simplest way I guess.

**Comment by cayolblake** [comment]
Well, `--ro-bind` does not follow symlinks for me, example, `/usr/lib64/libtinfo.so.6` is actually a link to `/usr/lib64/libtinfo.so.6.2` on the host, and attempting to bind it doesn't work.

Regardless of that, how do you think I should debug the created environment to spot what's created and what's not?

Any way to have an insight on the environment?

**Comment by cayolblake** [comment]
@rusty-snake To strip the problem down, I want to be able to debug why a certain binary (even the /bin/sh) not being able to find its libs, while I'm binding/copying/symlinking them through bwrap properly.

**Comment by cayolblake** [comment]
Yeah that's one way of doing it tho a bit twisted :)

Thanks to you, now I can have a view inside the environment, but I guess it would be a great addition if one where able to create the environment on disk, may be for creating a portable package if needed.

**Comment by smcv** [comment]
> I used to depend on linux-user-chroot and debugging was so easy in terms of when a binary cannot find its libs or any other dependencies.

If you want to pre-prepare a complete directory tree on-disk and "chroot" into it, you can do that: just mount it as the root (something like `bwrap --bind /opt/my-chroot / --dev /dev --bind /home /home /bin/bash`) and go from there. Mounting individual files into the tmpfs is an alternative to that, but you are not required to bind individual files if you don't want to.

Creating a persistent directory hierarchy by bind-mounting individual files in a way that is visible to processes outside the container is not possible unless you are root, because only root is allowed to manipulate the system-global mount namespace. bubblewrap works by creating a private mount namespace, which requires creating a private user namespace that is only directly visible to processes inside the container.

You can also inspect the container by looking at `/proc/12345/root`, where 12345 is the process ID of a process that is running inside the container.

**Comment by cayolblake** [comment]
@smcv the /proc/pid/root trick is what nails it if it's similar to chroots created for linux-user-chroot then that's all what's needed.

Will inspect the first command check the possibility of raising pre prepared chroots.

**Comment by cayolblake** [comment]
That did the trick and was able to access a file system point of view for the process.

Will keep experimenting with creating a portable micro container out of this.

Having this, honestly, I don't see the logic behind Docker given its overhead, unless I'm actually missing something in my understanding.

**Comment by rusty-snake** [comment]
You could also `--dev-bind / / --bind $chroot-base/usr/foo /usr/foo` to debug. Never mind the magic symlinks I totally forgot about are the best way.

> Having this, honestly, I don't see the logic behind Docker given its overhead, unless I'm actually missing something in my understanding.

Well, what is easier `docker run` or `bwrap --bind /foo /bat --bind ...` and for which of them do you need more knowledge about how your system works. 

Docker also has more network features, registries for images, snapshots, `pause, attach, kill, ...`.

FYI: https://github.com/projectatomic/bwrap-oci
