### ISSUE TITLE
Launching a flatpak breaks when symlink is present

### ISSUE THREAD

**Issue by notklaatu** [containers/bubblewrap#534]
I changed my `$HOME/Music` directory to a symlink pointing to an external drive, and afterwards bwrap aborted a [flatpak launch](https://github.com/flathub/com.valvesoftware.Steam/issues/985) with this error:

bwrap: Can't make symlink at /home/klaatu/Music: File exists

Changing my Music dir back to a real dir fixed the issue.

**Comment by smcv** [comment]
This has been a problem for a long time: it's something to do with `flatpak run --persist=.` combined with `flatpak run --filesystem=~/Music`, and is most commonly seen with Steam: https://github.com/flatpak/flatpak/issues/2387, https://github.com/flatpak/flatpak/issues/1971.

I think `bwrap` is doing the right thing here: Flatpak asked it to create a symlink, but that wasn't possible, so it failed. I don't think `bwrap` should be second-guessing what Flatpak asks it to do. Any solution to this should be in Flatpak, possibly supported by adding new options to `bwrap`.
