### ISSUE TITLE
Proper command to jail already created users

### ISSUE THREAD

**Issue by jaimbh** [containers/bubblewrap#536]
I ran the below commands as root to install bubblewrap in my ubuntu 18.04:
$ apt install pkg-config libcap-dev automake
$ git clone https://github.com/containers/bubblewrap.git
$ cd bubblewrap
$ git checkout v0.4.1
$ ./autogen.sh
$ make
$ make install
$ ln -s /usr/local/bin/bwrap /bin/bwrap
$ mv /usr/bin/bwrap /usr/bin/bwrap.dist
$ ln -s /usr/local/bin/bwrap /usr/bin/bwrap

Now I want to jail a linux user named danny so that danny will have access to only certain directories and files.
I want to restrict danny using your bubblewrap.
I read about containers, namespaces, cgroups, etc but I did not get any proper commands to jail/unjail a user.
I have searched everywhere.
But I am not understanding what commands to run as I am new to this.
I just want the proper commands to jail-shell a user.
Please help.

**Comment by smcv** [comment]
> I just want the proper commands to jail-shell a user

bwrap does not provide this. It's more mechanism than policy, and is mainly used to help to implement higher-level frameworks like Flatpak.

If someone (maybe you?) wants to write a generic "jail shell" framework, then bwrap might be a useful thing to use as part of implementing that framework, but a ready-made solution to what you want to do is outside bwrap's scope.
