### ISSUE TITLE
Add option to set 'nosetuid' on bind mounts

### ISSUE THREAD

**Issue by RalfJung** [containers/bubblewrap#546]
I would be nice to be able to apply an extra level of hardening by entirely preventing the sandbox from running setuid binaries, via the `nosetuid` mount flag. Currently I cannot see a way to set such a flag for bind mounts.

**Comment by rusty-snake** [comment]
I assume you mean `nosuid` because `nosetuid` is unknown to me.

Which option does not set `MS_NOSUID`? AFAIK all options in bubblewrap use it as hardcoded default.

**Comment by smcv** [comment]
> preventing the sandbox from running setuid binaries

bubblewrap already uses `PR_SET_NO_NEW_PRIVS`, which means the setuid bit, the setgid bit and file capabilities are all ignored.

**Comment by RalfJung** [comment]
Oh you are right. I was surprised that things like `mount` and `ping` worked in bubblewrap when they did not work in firejail, but that seems unrelated. Sorry for the noise and thanks!

**Comment by rusty-snake** [comment]
Both, mount and ping, do not necessarily fail inside firejail. ping even has an own profile. However `mount` (the binary) is backlisted and ping becomes complicated if you set `force-nonewprivs` and your kernel does not allow unprivileged userns clone (and other cases/conditions).

**Comment by RalfJung** [comment]
Yeah the sheer complexity of firejail is one reason why I am migrating towards flatpak and bubblewrap. :) And I am quite happy I can use more tools inside these sandboxes now -- first I thought this was indicative of a less secure configuration, but it seems that is not the case so all is well. Thanks for working on bubblewrap. :)
