### ISSUE TITLE
$ORIGIN in RPATH doesn't seem to work properly 

### ISSUE THREAD

**Issue by russelltg** [containers/bubblewrap#565]
Given this example:

```bash
echo 'const char* library_function() { return "Hello from shared library"; }' > lib.c
echo '#include <stdio.h>
extern const char* library_function(); int main() { printf("%s", library_function()); }' > main.c

mkdir -p bin lib
gcc lib.c -shared -o lib/libdep.so
gcc main.c -L lib -l dep -Wl,-rpath=\$ORIGIN/../lib -o bin/app
```

Which works fine unsandboxed:

```bash
$ ./bin/app
Hello from shared library
```

Doesn't seem to work properly in `bwrap`:

```bash
$ bwrap --ro-bind /usr /usr --symlink usr/lib /lib64 --ro-bind /etc /etc --dir /var --dir /run --dev /dev --ro-bind . /app /app/bin/app
/app/bin/app: error while loading shared libraries: libdep.so: cannot open shared object file: No such file or directory
```

But it does work with `LD_LIBRARY_PATH`:

```bash
$ LD_LIBRARY_PATH=/app/lib bwrap --ro-bind /usr /usr --symlink usr/lib /lib64 --ro-bind /etc /etc --dir /var --dir /run --dev /dev --ro-bind . /app /app/bin/app
Hello from shared library
```

Is this expected? Am I reporting this in the correct location?

My system: Updated arch linux as on 03 March 2023, bubblewrap 0.7.0

**Comment by hartwork** [comment]
Hi @russelltg ,

once I replace `--symlink usr/lib /lib64` by `--ro-bind /lib64 /lib64`, your examples work the same way for me, so I can confirm that with `LD_LIBRARY_PATH` (or `--setenv LD_LIBRARY_PATH /app/lib`) things work while without they don't.
PS: Arch has 0.8.0 [by now](https://repology.org/project/bubblewrap/versions).

Best, Sebastian

**Comment by rusty-snake** [comment]
It's because you doesn't mount a procfs.

```console
$ unshare -r -m
# ./bin/app
Hello from shared library
# mount -t tmpfs tmpfs /proc
# ./bin/app
./bin/app: error while loading shared libraries: libdep.so: cannot open shared object file: No such file or directory
```

Implementing `$ORIGIN` via `/proc/{pid|self}/exe` or so is rather reasonable.

**Comment by smcv** [comment]
It seems bubblewrap is doing what you tell it to do, even if what you tell it to do is not what you actually wanted (like not having a `/proc`), so this is working as intended.

In practice you'll nearly always want `--proc` if you are using `--unshare-pid` or `--unshare-all`, or `--bind /proc /proc` (or a variation like `--ro-bind`) if you are not.
