### ISSUE TITLE
Question about Xwayland and python app.

### ISSUE THREAD

**Issue by BirdInFire** [containers/bubblewrap#568]
So in the past i have used a config for preventing xwayland to start with wayland app, the thing is now, when i remove the line that prevented it to start my app dont start at all with the error : 

At the start
Authorization required, but no authorization protocol specified

and in python
error: No available video device, 

there is no .Xautority in my home to bind (and flatpak don't seem to need it)

With try and fail to add thing from other example don't help me at all, so i ask here is someone can point out witch line miss (or break it).

I recall, i use Wayland gnome (fedora silverblue), and try to run this app (and eventually the app it will open), with xwayland. 

These is the settings i have now :

Thanks in advance for any help.

bwrap
--symlink usr/lib /lib
--symlink usr/lib64 /lib64
--symlink usr/bin /bin
--symlink usr/bin /sbin
--ro-bind /usr/lib /usr/lib
--ro-bind /usr/lib64 /usr/lib64
--ro-bind /usr/bin /usr/bin
--ro-bind /usr/share/applications /usr/share/applications
--ro-bind /usr/share/gtk-3.0 /usr/share/gtk-3.0
--ro-bind /usr/share/gtk-4.0 /usr/share/gtk-4.0
--ro-bind /usr/share/fontconfig /usr/share/fontconfig
--ro-bind /usr/share/drirc.d /usr/share/drirc.d
--ro-bind /usr/share/fonts /usr/share/fonts
--ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0
--ro-bind /usr/share/glvnd /usr/share/glvnd
--ro-bind /usr/share/icons /usr/share/icons
--ro-bind /usr/share/libdrm /usr/share/libdrm
--ro-bind /usr/share/mime /usr/share/mime
--ro-bind /usr/share/icons /usr/share/icons
--ro-bind /usr/share/mime /usr/share/mime
--ro-bind /etc/fonts /etc/fonts
--ro-bind /usr/share/X11/xkb /usr/share/X11/xkb
--dir /run/user/"$(id -u)"
--ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse
--ro-bind "/run/user/$(id -u)/pipewire-0" "/run/user/$(id -u)/pipewire-0"
--ro-bind /run/user/"$(id -u)"/wayland-0 /run/user/"$(id -u)"/wayland-0
--dev /dev
--dev-bind /dev/dri /dev/dri
--ro-bind /sys/dev/char /sys/dev/char
--proc /proc
--tmpfs /tmp
--bind /home/USERNAME/APP /home/USERNAME/APP
--bind /var/home/USERNAME/APP /var/home/USERNAME/APP <------ this line is because silverblue have the default home in /var/home the /home is a symlink)
--setenv HOME /var/home/USERNAME
--setenv PATH /usr/bin
--hostname RESTRICTED
--unshare-all
--die-with-parent
--new-session
APPLICATIONPATH.sh (who run .py)

**Comment by smcv** [comment]
Sorry, the maintainers of bubblewrap do not have enough time available for this project to be able to spend that time on teaching its users how to choose appropriate command-line arguments. We make the tool available, but how to use it is up to you.
