### ISSUE TITLE
ownership of /dev /console is changed within a b'wraped image

### ISSUE THREAD

**Issue by toralf** [containers/bubblewrap#581]
At a stable hardened Gentoo Linux I do see this permissions:
```
$ ls -l /dev/console 
crw------- 1 root root 5, 1 Jun  5 13:36 /dev/console
```
whilst within a b'wraped image for user _tinderbox_ I do have:
```
$ ls -l /dev/console 
crw--w---- 1 tinderbox tty 136, 0 Jun  8 16:38 /dev/console
```

Both owner, group and the perms do differ. Most  other files under /dev does not show this change AFAICS.

This breaks at least breaks the test phase of the package dev-libs/poco here  under a stable hardened Gentoo Linux (https://bugs.gentoo.org/907864).

The code to call to bubblewrap is here: https://github.com/toralf/tinderbox/blob/main/bin/bwrap.sh#L127.

**Comment by smcv** [comment]
This appears to be working as designed.

`--dev /dev` is documented to create a minimal `/dev`, and therefore only creates the small number of basic devices that the Linux kernel allows unprivileged users to create inside a user namespace (the most important being `/dev/null` and `/dev/random`).

bwrap is primarily designed to be run by unprivileged users to sandbox individual applications or application components (for example as part of Flatpak or libgnome-desktop) and isn't really designed to be a faithful emulation of a full system, so it generally limits itself to things that unprivileged users would be allowed to do, even if run with full root privileges. From a sandboxing point of view, if bwrap did the equivalent of `mknod /dev/console c 5 1` when run with privileges, that would likely weaken the sandbox - I think there are ioctls that can be done on char device 5:1 that alter global system state, but if you're sandboxing your builds with bwrap, then presumably you don't want that sort of thing to be possible.

You can use `--dev-bind` to expose any other device nodes from the real `/dev`, if you want to, but again that weakens the sandbox.

If you run bwrap interactively (with a terminal as its stdout), then `/dev/console` is special-cased to be a bind-mount of whatever terminal bwrap has as its stdout, as if via `--dev-bind $(tty) /dev/console`:

```
          /* If stdout is a tty, that means the sandbox can write to the
             outside-sandbox tty. In that case we also create a /dev/console
             that points to this tty device. This should not cause any more
             access than we already have, and it makes ttyname() work in the
             sandbox. */
          if (host_tty_dev != NULL && *host_tty_dev != 0)
            {
              cleanup_free char *src_tty_dev = strconcat ("/oldroot", host_tty_dev);
              cleanup_free char *dest_console = strconcat (dest, "/console");

              if (create_file (dest_console, 0444, NULL) != 0)
                die_with_error ("creating %s/console", op->dest);

              privileged_op (privileged_op_socket,
                             PRIV_SEP_OP_BIND_MOUNT, BIND_DEVICES, 0, 0,
                             src_tty_dev, dest_console);
            }
```

and therefore it inherits the ownership of that terminal. You can make bwrap's standard output be a pipe if that's not what you want, which will disable that behaviour. Compare:

```
bwrap --ro-bind / / --dev /dev ls -al /dev
bwrap --ro-bind / / --dev /dev ls -al /dev | cat
```

I suspect your experiments while investigating this were more like the first, and your sandboxed build was more like the second?

From the fact that you can see a uid/gid other than your own uid/gid and nobody/nogroup inside the container, I infer that you must be running bwrap as root. If that's the case, you could equally well use a more-fully-featured container manager that requires root privileges, like docker, lxc or systemd-nspawn (which require and provide real root privileges) or podman (which uses a setuid executable and `/etc/subuid` to let unprivileged users create relatively complete containers).

If Gentoo's packaging policy is that packages are allowed to assume a fully-featured Linux system with multiple uids, a relatively complete set of device nodes, etc. at build time, then bubblewrap is probably not going to be the right tool for sandboxed builds. You will need to either use a more fully-featured container manager, or patch packages so they avoid making those assumptions.

**Comment by toralf** [comment]
Understood.
FWIW the use case here is  QA check (aka "tinderboxing" in Gentoo) - so "--dev-bind" is what I probably will use.
Thx for the in-depth explanation!
