### ISSUE TITLE
does bubblewrap blocks syscall utimensat ?

### ISSUE THREAD

**Issue by toralf** [containers/bubblewrap#584]
A Gentoo dev does argue this in https://bugs.gentoo.org/907778#c11
I do wonder if that is right?

**Comment by rusty-snake** [comment]
Short: No.

Long: Bubblewrap with no special arguments does not block the syscall. However it can block the usage of the syscall (e.g. dropped capabilities, ...). An second option (the relevant if you talk about `ENOSYS`) are `--seccomp` and `--add-seccomp-fd` command line options that can be used to load a filter that blocks `utimensat`.

**Comment by toralf** [comment]
ah ok, thx
