### ISSUE TITLE
bwrap: Can't find source path /root/.cache/at-spi: Permission denied

### ISSUE THREAD

**Issue by Baerbeisser** [containers/bubblewrap#585]
System: Arch (well, Artix), all up to date

Conditions:
XDG_CACHE_HOME is set to $HOME/.cache
launching Evolution, Foliate (both using Bubblewrap) **as user**

**Comment by rusty-snake** [comment]
1. Where does `$HOME` points to?
2. Bwrap seems to behave correct here. The caller of bwrap requests `/root/.cache/at-spi` but the path is not accessible for the user. So if this isn't an issue with your system configuration, you should report it to whoever calls bwrap. Also note that there are soft versions of `--???-bind` that do not fail the start if a path does not exists: `--???-bind-try`.

**Comment by Baerbeisser** [comment]
Just solved it by regenrating /usr/share/mime/mime.cache.
I have `XDG_CACHE_HOME=$HOME/.cache` somewhere in `/etc/profile.d`, which gets called by login as root too. Guess after i once started something using this cache path as root, it got written in mime.cache?

Still though, systems mime.cache shouldn't affect user sessions. Does bubblewrap prefer systems mime.cache over users mime.cache?

**Comment by rusty-snake** [comment]
BWrap neither read nor knows about mime.cache. It's the program who calls BWrap (e.g. evolution).

**Comment by Baerbeisser** [comment]
So Evolution and Foliate and Flatpak (if you google the error message) all have the same bug occasionally over the last 2 years?

**Comment by rusty-snake** [comment]
They don't reinvent the wheel every time. They share code or use the same library.

**Comment by Baerbeisser** [comment]
Ooff, to track the source of the problem.
Well, thanks anyway!
