### ISSUE TITLE
Directory at /proc/{PID}/root doesn't match root of the sandbox

### ISSUE THREAD

**Issue by StandingPadAnimations** [containers/bubblewrap#589]
While debugging some issues related to portals (https://github.com/flatpak/xdg-desktop-portal/issues/1076), it seems like the `root` folder in `/proc/{PID}` (where `PID` is the PID of the command ran by `bwrap`) doesn't match what is expected in the sandboxed environment, which causes issues when trying to use portals.

For instance, I have a `.flatpak-info` file in the root folder of the sandboxed environment (required for portals to work correctly), but said file does not appear in the `root` folder of `/proc/{PID}`. 

Of course the program still reports the filesystem correctly, but other programs like `xdg-desktop-portal` will behave differently then intended

**Comment by rusty-snake** [comment]
WFM

Can you give more STR like bwrap command (as minimal as reproducible at best) and how you find the pid.

> required for portals to work correctly

- required for portals to work correctly *with flatpaks*
- for everything else that is not a flatpak, it is a hacky workaround to make one thing work and break two others or break your system (e.g. "if I copy it to my root directory as .flatpak-info, well things start getting funny with my desktop").
- Just to be clear that this is not something officially supported or recommended by the x-d-p authors.

**Comment by StandingPadAnimations** [comment]
Closing this since I realized it was user error
