### ISSUE TITLE
[How-to] Handle 'chroot' system calls as an unprivileged user

### ISSUE THREAD

**Issue by ruanformigoni** [containers/bubblewrap#590]
Hi there,

As a simple example, when running `pacman -S some_package` in a bwrap environment, I'm getting errors like:

```
(1/1) Arming ConditionNeedsUpdate...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
```

For my use-case, I can't run `bwrap` as root. Is there a feature to run system calls as an unprivileged user similar to `proot`? I think that to make this work I could use a custom `LD_PRELOAD` that overrides the `chroot` call to a nested `bwrap` instance instead. But I'd like to know if I missed something.

Thanks!

**Comment by ruanformigoni** [comment]
Just realized that using `fakechroot` inside the container, e.g., `fakechroot pacman -S some_package` works. :)

**Comment by smcv** [comment]
That will work, except for when it doesn't.

bubblewrap is not designed to emulate a complete operating system environment with multiple system users, and cannot do so. Inside the bubblewrap sandbox, kernel restrictions mean that there can only be two users: "me" and "not me". If you attempt to install an Arch package inside the sandbox that requires the use of uids other than 0, fakeroot will probably not be enough to make that work as intended.

If your goal is to put an entire operating system in a container, I would recommend looking into alternatives to bubblewrap such as unprivileged (rootless) podman or lxc/lxd, which rely on `/etc/subuid`, `/etc/subgid`, and setuid-root tools that read those files; or you could use a virtual machine.
