### ISSUE TITLE
What is a proper way to have a regular user with sudo and root in container?

### ISSUE THREAD

**Issue by dmikushin** [containers/bubblewrap#593]
Thanks for getting all of us to enjoy bubblewrap, cats included!

I think one important scenario would be to have the same regular user as for the host system in the container, plus sudo privileges for this user in container, plus a root user for sudo to work. What is your recommended setup for this scenario?

Without much understanding, on behalf of `--uid 0 --gid 0` I've tried to setup sudo package and user with same uid/gid as the host user. But sudo simply does not work, looks like it's not supported:

```
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Invalid argument
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

**Comment by smcv** [comment]
> have the same regular user as for the host system in the container, plus sudo privileges for this user in container, plus a root user for sudo to work

This is not something that bubblewrap can do. Kernel limitations mean that we can only create one user ID inside the container, and setuid binaries like sudo cannot work.

If you need a container with more than one uid available, please use a different container technology that uses `/etc/subuid`/`/etc/subgid` in conjunction with the setuid `newuidmap` helper (like Podman or unprivileged lxc/lxd), or requires root on the host system (like Docker or privileged lxc/lxd), or wraps one of those with a higher-level/more-user-friendly interface (like Toolbx, which uses Podman, or Distrobox, which uses either Podman or Docker).

I would personally recommend [Podman](https://podman.io/docs) and [Toolbx](https://containertoolbx.org/).

**Comment by dmikushin** [comment]
Thank you for this detailed explanation! I'm impressed how far the container technology has apparently advanced. You may want to know that awareness of these softwares is very low: most simply never heard of anything, but Docker. Let's spread the word about the cool tech that your develop!

**Comment by dmikushin** [comment]
About sudo I came up with the following. I simply keep two bubblewrap sessions open in tmux: one with `--uid 0 --gid 0`, and the second without. I switch between these two windows whenever I need to develop or install software. It's fairly comfortable. Some dnf packages like dbus fail to install due to chown error, though, I'm not sure why.
