### ISSUE TITLE
Bubblewrap trying to access `/proc/sys/kernel/overflowuid`

### ISSUE THREAD

**Issue by soumyaDghosh** [containers/bubblewrap#606]
As the title says, when using bubblewrap or invoking it from a separate code, and make it work, bubblewrap is trying to read `/proc/sys/kernel/overflowuid`. This is fine in regular packages, but in confined packages (eg: snaps), this behaviour is not expected. Is there any alternative/Has this been fixed in the latest versions?

**Comment by smcv** [comment]
bubblewrap requires this information, and cannot do its job correctly without it. If a confined package (e.g. Snap) wants to run bubblewrap, then the Snap confinement rules will need to allow it to read `/proc/sys/kernel/overflowuid` and `/proc/sys/kernel/overflowgid`.

(There are lots of other specialized things that bubblewrap needs and most apps don't, so any confined app that runs bubblewrap will already need a special profile.)
