### ISSUE TITLE
`bwrap` broke on Ubuntu 24.04

### ISSUE THREAD

**Issue by smoelius** [containers/bubblewrap#632]
Not sure if you guys are aware of this, but `bwrap` broke on Ubuntu 24.04.

See, e.g.:
- https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
- https://etbe.coker.com.au/2024/04/24/ubuntu-24-04-bubblewrap/

I searched Ubuntu's bug database and this is the closest one I could find: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844

This comment says that an AppArmor profile is coming for `bwrap`: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844/comments/115

Is this something that you guys would want to weigh in on?

**Comment by rusty-snake** [comment]
> Is this something that you guys would want to weigh in on?

Already happened in https://github.com/containers/bubblewrap/issues/505#issuecomment-2093203129

**Comment by smoelius** [comment]
Thanks, @rusty-snake. I wasn't aware of that comment in issue #505.

I should have been more clear, though. I meant: do the maintainers want to weigh in on the AppArmor profile that is coming for `bwrap`, as suggested by comment 115 of that thread.

I, personally, don't know how AppArmor profiles are constructed. But I imagine there are choices that might be made now that could be hard to fix down the road.

**Comment by smcv** [comment]
The bwrap maintainers do not have any control over what Canonical choose to do or not do in their distribution.

**Comment by smoelius** [comment]
OK. Thanks for replying, @smcv.

If I could just leave one final note for anyone that wants to try [the fix](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2064672/comments/4), the following commands seem to work:
```
sudo add-apt-repository ppa:apparmor-dev/apparmor-sru
sudo apt update
sudo apt install apparmor
```
