### ISSUE TITLE
slow python import 

### ISSUE THREAD

**Issue by achsvg** [containers/bubblewrap#638]
We're using bwrap in a docker container to run python scripts and noticed that python imports are much slower in the bwrap sandbox compared to the docker container:

```
time bwrap \
    --dir /tmp \
    --dir /var \
    --proc /proc \
    --dev /dev \
    --symlink /usr/lib /lib \
    --symlink /usr/lib64 /lib64 \
    --symlink /usr/bin /bin \
    --ro-bind /usr /usr \
    --ro-bind /home/user /home/user \
    --die-with-parent \
    --clearenv \
    --setenv HOME /home/user \
    --setenv PATH /home/user/anaconda3/bin:/usr/local/bin:/usr/bin:/bin \
    python -c "import pandas"

real	0m1.031s
user	0m1.024s
sys	0m0.320s
```

```
time python -c "import pandas"

real	0m0.346s
user	0m0.333s
sys	0m0.325s
```

Any ideas why this is the case? And if there is anything we can do to improve the performance?

**Comment by smcv** [comment]
My first guess would be that with the directory where `pandas` is installed mounted read-only, Python can't compile and cache `.pyc` files.

**Comment by achsvg** [comment]
Thanks! That was it.
