### ISSUE TITLE
Getting CLI ERROR spawn EINVAL when building an android project

### ISSUE THREAD

**Issue by EslamElbyaly** [containers/bubblewrap#640]
I'm trying to install bubblewrap CLI through Node.js on Windows 11 Home edition then initiate and build an android project to call a PWA.
I downloaded Node.js then installed it successfully without the additional tools. As you might know, there's a checkbox that user can tick if they need to install the additional tools. I did not do that, and installed only Node.js.
After that, I opened CMD and ran `npm i -g @bubblewrap/cli`. I got the following output...

    npm warn deprecated @types/minipass@3.3.5: This is a stub types definition. minipass provides its own type definitions, so you do not need this installed.
    npm warn deprecated @types/gapi.client.androidpublisher@3.0.2: use @types/gapi.client.androidpublisher-v3 instead; see https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/652 for details
    npm warn deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
    
    changed 266 packages in 33s
    
    30 packages are looking for funding
      run `npm fund` for details
Then I used `bubblewrap init --manifest my_pwa_manifest_Url` and got...

    (node:11124) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    (Use `node --trace-deprecation ...` to show where the warning was created)
    ? Do you want Bubblewrap to install the JDK (recommended)?

--------------------------------------------
I entered Y for it and Y for other questions to download the Android SDK and for agreeing the Android SDK terms. 
It started the initialization process of the app, and I started answering the prompt till I got "Project generated successfully.
When tried to build the project using `bubblewrap build`, I got 

(node:12536) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

and it asked to agree to the terms of installing build tools and I said Yes then after that I got `cli ERROR spawn EINVAL`.
P.S: I tried many versions of Node.js 20.15, 19.9, 18.20.3 and 22.3.

**Comment by rusty-snake** [comment]
Sure that you are on the right bubblewrap repo?

If so, install it directly in your WSL2 without any node/java/android overhead.

**Comment by EslamElbyaly** [comment]
> Sure that you are on the right bubblewrap repo?
Not sure what you mean with "repo", but I downloaded it from here...
https://github.com/GoogleChromeLabs/bubblewrap/tree/main/packages/cli
> If so, install it directly in your WSL2 without any node/java/android overhead.
Is this what you're referring to with "WSL 2"?
https://learn.microsoft.com/en-us/windows/wsl/about

**Comment by rusty-snake** [comment]
> ***GoogleChromeLabs***/bubblewrap

This repo is ***containers***/bubblewrap.

**Comment by EslamElbyaly** [comment]
> This repo is containers/bubblewrap.
What's that mean? 
Pardon me, I am new to Github.

**Comment by rusty-snake** [comment]
This is a different software also named bubblewrap (this one is older, G "stole" its name).
You will have to ask at https://github.com/GoogleChromeLabs/bubblewrap/discussions.

**Comment by EslamElbyaly** [comment]
Oops! Sorry for that. Thanks for letting me know.

**Comment by rusty-snake** [comment]
You're welcome.

**Comment by smcv** [comment]
Not this project's issue, closing.
