### ISSUE TITLE
Broken for uid/gids >= 2^31

### ISSUE THREAD

**Issue by ethanbb** [containers/bubblewrap#642]
I'm using a machine where user and group ids corresponding to Active Directory identities are in the upper range of uint32 values (>= 2^31). I encountered the following error whenever trying to use `bwrap`: 

`bwrap: setting up uid map: Invalid argument`

I realized that was because `bwrap` is interpreting the uid and gid as signed integers and therefore negative when writing to `uid_map`; trying to write negative values causes the EINVAL error. I realize that it is an edge case and perhaps undefined behavior. However, I found that making the following changes fixed my problem. I didn't want to submit a PR because I don't know if this will cause other problems (willing to risk it on this machine, but somebody who knows what they're doing should take a closer look).

```diff
diff --git a/bubblewrap.c b/bubblewrap.c
index c414bb0..8400bcb 100644
--- a/bubblewrap.c
+++ b/bubblewrap.c
@@ -971,16 +971,16 @@ write_uid_gid_map (uid_t sandbox_uid,
     die_with_error ("open /proc/%s failed", dir);
 
   if (map_root && parent_uid != 0 && sandbox_uid != 0)
-    uid_map = xasprintf ("0 %d 1\n"
-                         "%d %d 1\n", overflow_uid, sandbox_uid, parent_uid);
+    uid_map = xasprintf ("0 %u 1\n"
+                         "%u %u 1\n", overflow_uid, sandbox_uid, parent_uid);
   else
-    uid_map = xasprintf ("%d %d 1\n", sandbox_uid, parent_uid);
+    uid_map = xasprintf ("%u %u 1\n", sandbox_uid, parent_uid);
 
   if (map_root && parent_gid != 0 && sandbox_gid != 0)
-    gid_map = xasprintf ("0 %d 1\n"
-                         "%d %d 1\n", overflow_gid, sandbox_gid, parent_gid);
+    gid_map = xasprintf ("0 %u 1\n"
+                         "%u %u 1\n", overflow_gid, sandbox_gid, parent_gid);
   else
-    gid_map = xasprintf ("%d %d 1\n", sandbox_gid, parent_gid);
+    gid_map = xasprintf ("%u %u 1\n", sandbox_gid, parent_gid);
```

**Comment by smcv** [comment]
> I'm using a machine where user and group ids corresponding to Active Directory identities are in the upper range of uint32 values (>= 2^31).

Not all Linux kernel features are expected to work in this uid/gid range: `uid_t` and `gid_t` are defined to be signed 32-bit types, and for example https://elixir.bootlin.com/linux/v6.10/source/include/net/ping.h only supports setting the `net.ipv4.ping_group_range` sysctl to the lower half of the unsigned range.

I'd recommend migrating to the lower half of the unsigned range if at all possible. systemd's https://systemd.io/UIDS-GIDS/ documents the upper half like this:

> Note that the range 2147483648…4294967294 (i.e. 2^31…2^32-2) should be handled with care. Various programs (including kernel file systems — see devpts — or even kernel syscalls – see setfsuid()) have trouble with UIDs outside of the signed 32-bit range, i.e any UIDs equal to or above 2147483648. It is thus strongly recommended to stay away from this range in order to avoid complications. This range should be considered reserved for future, special purposes.

**Comment by smcv** [comment]
> I didn't want to submit a PR because I don't know if this will cause other problems

If you're unwilling to send a PR, then we're unlikely to make that change either.

I would personally want to get someone with a more in-depth knowledge of user namespaces and their security properties to review such a PR - I'm the most active reviewer, but I don't consider myself qualified to say whether the change you propose would be valid or not.

**Comment by ethanbb** [comment]
> If you're unwilling to send a PR, then we're unlikely to make that change either.

I could easily make a PR. I'm just hesitant because I recently had an experience where I made a PR to a very widely-used package, it wasn't reviewed very rigorously, and it turned out to have a subtle (to me) bug that broke many Python developers' CI pipelines for about 15 minutes. It sounds like this repo does have a more rigorous review process, but since I don't need personally need the change anymore as I've built from source, I'd probably still want to hold off unless others in the community want it.

**Comment by ethanbb** [comment]
> I'd recommend migrating to the lower half of the unsigned range if at all possible. systemd's https://systemd.io/UIDS-GIDS/ documents the upper half like this:

Thanks for alerting me to this. After some more investigating, I think this is probably not worth fixing as there are at least a few other things  broken on my system due to being in that high UID range anyway. And I did eventually figure out a way to avoid using that range.
