### ISSUE TITLE
Why it's not working ? 

### ISSUE THREAD

**Issue by RENANZG** [containers/bubblewrap#649]
<p>I want to use <code>bwrap</code> with FreeTube.AppImage</p>

<p>It must work in Xfce, LxQt and GNOME environments.</p>

<p>How to debug it ? With <code>strace</code>?</p>

<p>The AppImage works with these board permissions:</p>

<pre><code>
bwrap --cap-add CAP_SYS_ADMIN --dev-bind / / --ro-bind /home/user/.local/share/AppImages/freetube/freetube.AppImage /home/user/.local/share/AppImages/freetube/freetube.AppImage sh -c '/home/user/.local/share/AppImages/freetube/freetube.AppImage'
</code></pre>

<p>It does not work with these more restricted permissions:</p>

<pre><code>
  bwrap \
  --dev-bind /dev /dev \
  --ro-bind /home/user/.local/share/AppImages/freetube/freetube.AppImage /home/user/.local/share/AppImages/freetube/freetube.AppImage \
  --bind /tmp /tmp \
  --bind /run/user/1000/pulse /run/user/1000/pulse \
  --bind /home/user/.Xauthority /home/user/.Xauthority \
  --bind /tmp/.X11-unix /tmp/.X11-unix \
  --proc /proc \
  --ro-bind /etc/ssl /etc/ssl \
  --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
  --ro-bind /lib /lib \
  --ro-bind /lib64 /lib64 \
  --ro-bind /usr/lib /usr/lib \
  --ro-bind /usr/lib64 /usr/lib64 \
  --bind /home/user/.config/freetube /home/user/.config/freetube \
  --bind /home/user/.local/share/freetube /home/user/.local/share/freetube \
  --tmpfs /tmp \
  --cap-add CAP_SYS_ADMIN \
  sh -c '/home/user/.local/share/AppImages/freetube/freetube.AppImage'
</code></pre>

<details>
<summary>Other attempts</summary>
<br>
<pre><code>
bwrap --ro-bind / / \
      --dev /dev \
      --proc /proc \
      --tmpfs /tmp \
      --ro-bind /etc /etc \
      --ro-bind /lib /lib \
      --ro-bind /lib64 /lib64 \
      --ro-bind /usr /usr \
      --dev-bind /dev/fuse /dev/fuse \
      /home/user/.local/share/AppImages/freetube/freetube.AppImage
      
      
      Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory

</code></pre>
<pre><code>
sudo bwrap --unshare-all \
           --ro-bind / / \
           --dev /dev \
           --proc /proc \
           --tmpfs /tmp \
           --ro-bind /etc /etc \
           --ro-bind /lib /lib \
           --ro-bind /lib64 /lib64 \
           --ro-bind /usr /usr \
           --dev-bind /dev/fuse /dev/fuse \
           /home/user/.local/share/AppImages/freetube/freetube.AppImage
           
           
           bwrap: execvp /home/user/.local/share/AppImages/freetube/freetube.AppImage: Permission denied
</code></pre>
</details>

<details>
<summary>The complete proposed script to install FreeTube.AppImage</summary>
<br>

<pre><code class="bash">
#!/usr/bin/env bash

########################################################################
# File Name    : install_freetube_appimage.sh
# Description  : This script automates the installation and setup of
#                an AppImage application. It downloads the latest
#                version from a specified source using curl, installs
#                it to the user's home directory, creates necessary
#                directories and symbolic links, provides an updater
#                script and a remover script, and runs the AppImage
#                inside a bubblewrap (bwrap) sandbox for added security.
# Dependencies : curl, bubblewrap, rsvg-convert (if available,
#                convert the SVG icon to PNG format)
# Usage        : • Make the script executable with
#                  chmod +x install_freetube_appimage.sh
#                • Run the script with:
#                  bash install_freetube_appimage.sh
#                • To uninstall the AppImage, run:
#                  bash $HOME/.local/share/freetube/remover.sh
# Author       : Me and the bois
# License      : Free of charge, no warranty
# Inspired by  : https://portable-linux-apps.github.io
########################################################################

# Ensure shell script safety checks
set -u

# Define variables
APP_NAME="freetube"
APP_DOWNLOAD_URL="https://api.github.com/repos/FreeTubeApp/FreeTube/releases"
HOME_DIR="$HOME/.local/share/AppImages/$APP_NAME"
EXTRACTED_DIR="$HOME_DIR/squashfs-root"
APPIMAGE_FILE="$HOME_DIR/$APP_NAME.AppImage"
ICON_DIR="$HOME_DIR/icon"
DESKTOP_ENTRY="$HOME/.local/share/applications/$APP_NAME.desktop"

# Bubblewrap command options
BWRAP_CMD="bwrap"
BWRAP_OPTS="
--dev-bind /dev /dev \
--ro-bind $APPIMAGE_FILE $APPIMAGE_FILE \
--dev-bind /dev/dri /dev/dri \
--bind /tmp/.X11-unix /tmp/.X11-unix \
--bind $XAUTHORITY $XAUTHORITY \
--bind /run/user/$UID/pulse /run/user/$UID/pulse \
--ro-bind /etc/ssl /etc/ssl \
--ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
--ro-bind /lib /lib \
--ro-bind /lib64 /lib64 \
--ro-bind /usr/lib /usr/lib \
--ro-bind /usr/lib64 /usr/lib64 \
--proc /proc \
--tmpfs /tmp \
--bind $HOME/Downloads $HOME/Downloads \
--bind $HOME/.config/$APP_NAME $HOME/.config/$APP_NAME \
--bind $HOME/.local/share/$APP_NAME $HOME/.local/share/$APP_NAME \
sh -c \"$APPIMAGE_FILE\"
"

# Define and create necessary directories
mkdir -p "$HOME_DIR" "$ICON_DIR" "$HOME/.local/share/applications"
mkdir -p "$HOME/Downloads"
mkdir -p "$HOME/.config/$APP_NAME"
mkdir -p "$HOME/.local/share/$APP_NAME"

# Function to download AppImage
download_appimage() {
    VERSION_URL=$(curl -sL "$APP_DOWNLOAD_URL" | grep -o '"browser_download_url": *"[^"]*"' | grep -o 'https://[^"]*' | grep -i 'amd64.*\.AppImage\|x86_64.*\.AppImage' | head -n 1)
    if [ -z "$VERSION_URL" ]; then
        echo "Error: Unable to find AppImage URL."
        exit 1
    fi

    echo "Downloading AppImage from $VERSION_URL..."
    if ! curl -L -o "$APPIMAGE_FILE" "$VERSION_URL"; then
        echo "Error: Failed to download AppImage."
        exit 1
    fi
    chmod a+x "$APPIMAGE_FILE"
}

# Function to extract AppImage
extract_appimage() {
    echo "Extracting AppImage from $APPIMAGE_FILE..."

    # Ensure the AppImage file exists
    if [ ! -f "$APPIMAGE_FILE" ]; then
        echo "Error: AppImage file not found at $APPIMAGE_FILE."
        exit 1
    fi

    # Perform extraction
    echo "Running AppImage extraction command..."
    if ! "$APPIMAGE_FILE" --appimage-extract > /dev/null 2>&1; then
        echo "Error: Failed to extract AppImage using --appimage-extract."
        exit 1
    fi

    echo "Extraction completed. Moving extracted files to $EXTRACTED_DIR..."
    
    # Move extracted files to the correct directory
    if [ -d "$HOME/squashfs-root" ]; then
        mv "$HOME/squashfs-root" "$EXTRACTED_DIR"
    fi

    # Verify extraction directory exists
    if [ ! -d "$EXTRACTED_DIR" ]; then
        echo "Error: Extraction directory not found at $EXTRACTED_DIR."
        exit 1
    fi
}

# Function to handle extracted files
handle_extracted_files() {
    echo "Handling extracted files..."
    
    # Find the desktop entry and icon file
    DESKTOP_ENTRY_SRC=$(find "$EXTRACTED_DIR" -name "$APP_NAME.desktop" | head -n 1)
    ICON_FILE=$(find "$EXTRACTED_DIR" -name "$APP_NAME.svg" | head -n 1)

    # Debugging information
    echo "Desktop entry source: $DESKTOP_ENTRY_SRC"
    echo "Icon file: $ICON_FILE"

    # Check if the desktop entry file is found
    if [ -z "$DESKTOP_ENTRY_SRC" ]; then
        echo "Error: Desktop entry file not found in the AppImage."
        exit 1
    fi

    # Check if the icon file is found
    if [ -z "$ICON_FILE" ]; then
        echo "Error: Icon file not found in the AppImage."
        exit 1
    fi

    # Convert the SVG icon to PNG format if rsvg-convert is available
    ICON_PATH="$ICON_DIR/$APP_NAME.png"
    if command -v rsvg-convert &> /dev/null; then
        echo "Converting SVG to PNG..."
        if ! rsvg-convert -o "$ICON_PATH" "$ICON_FILE"; then
            echo "Error: Failed to convert SVG to PNG."
            exit 1
        fi
    else
        echo "Warning: rsvg-convert is not installed. Using SVG icon instead."
        ICON_PATH="$ICON_DIR/$APP_NAME.svg"
        cp "$ICON_FILE" "$ICON_PATH"
    fi

    # Copy the desktop entry to the appropriate location
    cp "$DESKTOP_ENTRY_SRC" "$DESKTOP_ENTRY"
    if [ ! -f "$DESKTOP_ENTRY" ]; then
        echo "Error: Failed to copy desktop entry."
        exit 1
    fi

    # Convert multi-line BWRAP_OPTS to a single line
    BWRAP_OPTS_SINGLE_LINE=$(echo "$BWRAP_OPTS" | tr -d '\n' | sed 's/ *\\ / /g')

    # Modify the desktop entry to use bubblewrap
    sed -i "s|^Exec=.*|Exec=$BWRAP_CMD $BWRAP_OPTS_SINGLE_LINE|g" "$DESKTOP_ENTRY"
    sed -i "s|^Icon=.*|Icon=$ICON_PATH|g" "$DESKTOP_ENTRY"

    echo "Desktop entry and icon have been set up successfully."

    # Remove the extracted directory
    echo "Cleaning up extracted files..."
    rm -rf "$EXTRACTED_DIR"
}

# Download, extract, and handle files
download_appimage
extract_appimage
handle_extracted_files

# Add remover script
cat > "$HOME_DIR/remover.sh" <<EOF
#!/bin/sh
set -e
rm -f \$HOME/.local/share/applications/$APP_NAME.desktop
rm -rf $HOME_DIR
rm -f \$HOME/Desktop/$APP_NAME.desktop
rm -f \$HOME/.config/$APP_NAME
rm -f \$HOME/.local/share/$APP_NAME
gtk-update-icon-cache \$HOME_DIR/icon > /dev/null 2>&1
echo "Application removed."
EOF
chmod a+x "$HOME_DIR/remover.sh"

# Script to update the program
cat > "$HOME_DIR/updater.sh" <<EOF
#!/bin/sh
set -u
APP_NAME="$APP_NAME"
APP_DOWNLOAD_URL="$APP_DOWNLOAD_URL"
HOME_DIR="$HOME_DIR"
version=\$(curl -sL "\$APP_DOWNLOAD_URL" | grep -o '"browser_download_url": *"[^"]*"' | grep -o 'https://[^"]*' | grep -i 'amd64.*\.AppImage\|x86_64.*\.AppImage' | head -n 1)
if [ -n "\$version" ]; then
    mkdir -p "\$HOME_DIR/tmp" && cd "\$HOME_DIR/tmp" || exit 1
    curl -L -o "\$APP_NAME.AppImage" "\$version" || exit 1
    mv "\$APP_NAME.AppImage" "\$HOME_DIR/\$APP_NAME.AppImage"
    chmod a+x "\$HOME_DIR/\$APP_NAME.AppImage" || exit 1
    echo "\$version" > "\$HOME_DIR/version
    rm -rf "\$HOME_DIR/tmp"
    notify-send "\$APP_NAME is updated!"
    gtk-update-icon-cache "$HOME_DIR/icon" > /dev/null 2>&1
else
    echo "Update not needed!"
fi
EOF
chmod a+x "$HOME_DIR/updater.sh"

# Update desktop database and icon cache silently
update-desktop-database "$HOME/.local/share/applications" > /dev/null 2>&1
gtk-update-icon-cache "$HOME_DIR/icon" > /dev/null 2>&1

# Copy .desktop file to the Desktop
cp "$DESKTOP_ENTRY" "$HOME/Desktop"

# GNOME-specific steps
if command -v gnome-shell &> /dev/null; then
    # Trigger a GNOME Shell refresh
    gnome-shell-extension-tool -r || killall -3 gnome-shell
fi

echo "Installation completed successfully."
</code></pre>

</details>

<details>
<summary>Generic explanaions of the commands</summary>
<br>
<pre>
--dev-bind /dev /dev: Bind the /dev directory to allow access to device files, including /dev/fuse needed for FUSE.
--ro-bind /home/user/.local/share/AppImages/freetube/freetube.AppImage /home/user/.local/share/AppImages/freetube/freetube.AppImage: Read-only bind mount of the AppImage.
--bind /tmp /tmp: Bind /tmp to ensure temporary files can be created.
--bind /run/user/1000/pulse /run/user/1000/pulse: Bind PulseAudio socket for sound.
--bind /home/user/.Xauthority /home/user/.Xauthority: Bind Xauthority file for X11 authentication.
--bind /tmp/.X11-unix /tmp/.X11-unix: Bind X11 UNIX domain sockets for graphical applications.
--proc /proc: Bind /proc to access process information.
--ro-bind /etc/ssl /etc/ssl: Read-only bind mount of SSL certificates for secure communications.
--ro-bind /usr/share/ca-certificates /usr/share/ca-certificates: Read-only bind mount of CA certificates.
--ro-bind /lib /lib, --ro-bind /lib64 /lib64, --ro-bind /usr/lib /usr/lib, --ro-bind /usr/lib64 /usr/lib64: Read-only bind mounts of libraries.
--bind /home/user/.config/freetube /home/user/.config/freetube: Bind mount the configuration directory for FreeTube.
--bind /home/user/.local/share/freetube /home/user/.local/share/freetube: Bind mount the data directory for FreeTube.
--tmpfs /tmp: Use a temporary filesystem for /tmp.
--cap-add CAP_SYS_ADMIN: Add CAP_SYS_ADMIN capability needed for mounting and other operations.

Adjustments
- User ID (UID): Replace 1000 in /run/user/1000/pulse with the actual UID of the user running the command if it's different.
- Paths: Adjust paths based on your environment and the specific requirements of the AppImage.
</pre>
</details>

**Comment by rusty-snake** [comment]
First, this is a issue tracker not a support forum.
Second, environment information are missing. Is bwrap suid? (Relevant for FUSE) Which distro do you use? (Based on the paths in your script I guess something Debian based?) 

> How to debug it ? With strace?

strace is always a possibility. However the effort is mid-high so you should start simpler.

Since you know that `--dev-bind / /` works, you can narrow the required paths down. Start with all paths (i.e. `for file in /*; do printf "--dev-bind %s %s " $file $file; done`), make sure it works, remove one, test again, remove the next, ... .

**Comment by smcv** [comment]
Sorry, we do not have the resources to debug arbitrary uses of bubblewrap for arbitrary applications. If you believe there's a bug in bubblewrap that is being exposed by this use-case, please try to construct a more minimal reproducer for it.

**Comment by RENANZG** [comment]
Using bubblewrap’s arguments is just perfect for those who enjoy making security mistakes without any help from a convenience layer.

**Comment by smcv** [comment]
> Using bubblewrap’s arguments is just perfect for those who enjoy making security mistakes without any help from a convenience layer.

Yes: as the readme says, it's a toolkit for building your own sandboxes, not a ready-made sandbox. If what you want is a ready-made sandbox with its own security policies that makes use of bubblewrap behind the scenes, Flatpak is one example of that.
