### ISSUE TITLE
make prctl(PR_SET_NO_NEW_PRIVS optional

### ISSUE THREAD

**Issue by hubert-tonneau** [containers/bubblewrap#654]
Hi,

Here is the scenario:
A small minimal system is used to administer several systems inside containers.
In one of the containers /fulllinux, we expect to run a full Linux system, with plain access to the hardware, so that it has no time execution penality or small issue any container will bring with. On the other end, the container is not expected to provide additional security. The container is just for maintenance since it can be remotely stopped, upgraded, restarted.

Solution 1: chroot
chroot /fulllinux  /lib/systemd/systemd --system
Will not work at all because systemd will complain that it's PID is not 1. No comment.

Solution 2: unshare
unshare --pid --fork --kill-child --mount --root=/fulllinux /lib/systemd/systemd --system
Inside the full Linux container, bwrap will not work as non root.

Solution 3: bwrap
bwrap --unshare-pid --as-pid-1 --dev-bind /fulllinux / /lib/systemd/systemd --system
Inside the full Linux containter, su will not work because bwrap disabled su executable suid flag through calling prctl(PR_SET_NO_NEW_PRIVS optional

Solution 4: patched bwrap
bwrap --promiscuous --unshare-pid --as-pid-1 --dev-bind /fulllinux / /lib/systemd/systemd --system
No issue noticed :-)

[bwrap-promiscuous.txt](https://github.com/user-attachments/files/16944132/bwrap-promiscuous.txt)

**Comment by rusty-snake** [comment]
Solution 5: systemd-nspawn

**Comment by smcv** [comment]
Yes, please use something like `systemd-nspawn` or `chroot` for this use-case. bwrap is not intended to be the single solution to every container-related problem anyone might have, and running full systems is outside its scope.

**Comment by hubert-tonneau** [comment]
Thanks for your suggestion ... but

Solution 5:
systemd-nspawn -b -D /fulllinux
Fails with error message 'Failed to open system bus: No such file or directory'
Seems like a chicken and eggs problem. In order to start systemd, you need to have systemd running.
