### ISSUE TITLE
--level-prefix=7 seems not to work for openrc ?

### ISSUE THREAD

**Issue by toralf** [containers/bubblewrap#669]
I added the option to https://github.com/toralf/tinderbox/blob/main/bin/bwrap.sh#L85 but got
```
bwrap: Unknown option --level-prefix=7
```
at a hardened Gentoo linux with OpenRC (no systemd).

**Comment by rusty-snake** [comment]
There is no option named `--level-prefix=7`. However there is a similar option: `--level-prefix` which modifies the output of bwrap to contain the log severity of the message.

**Comment by toralf** [comment]
oh - my fault.
