### ISSUE TITLE
Host mounted dirs are always mounted? - Strange mount output

### ISSUE THREAD

**Issue by tg44** [containers/bubblewrap#673]
I have a docker container. The container runs a small js service, which enables code compile/run in that given container, for multiple users. Also, we have a mounted directory in the container (its an nfs mount). (We are using this setup, because mounting the subdirs of `teamsProjects` to our container is slow as hell, but also I want to hide the subdirs, and want to create an as separate environment as possible, as fast as possible, so instead of starting a separate container for a project, we want to isolate it inside.)

I have a small init script;
```js
const bubblewrapCommand = (projectId, commandArgs) => {
    const bubblewrap = [
        "sudo bwrap",
        `--unshare-all`, // Unshare all namespaces for isolation
        `--new-session`, // Create a new session
        `--die-with-parent`, // Die with parent process
        `--hostname test`,
        //'--dir /root',
        `--dev /dev`, // Include /dev for basic device access
        //`--proc /proc`, // Include /proc for basic process access
        `--tmpfs /tmp`, // Provide isolated /tmp
        `--ro-bind-try /usr/bin /bin`, // Make /bin read-only
        `--ro-bind-try /usr/lib /lib`, // Make /bin read-only
        `--ro-bind-try /usr/lib32 /lib32`,
        `--ro-bind-try /usr/lib64 /lib64`,
        `--ro-bind-try /usr/libx32 /libx32`,
        `--ro-bind-try /usr/include /include`,
        `--ro-bind-try /usr/share /share`,
        `--ro-bind-try /usr/local /local`,
        `--ro-bind-try /usr/sbin /sbin`,
        `--ro-bind-try /usr/src /src`,
        `--ro-bind-try /usr/libexec /libexec`,
        `--ro-bind-try /usr /usr`, // Make /usr read-only
        `--tmpfs /var`, // Provide isolated /var
        `--tmpfs /mnt`, //try to unbind /mnt for sure
        `--bind /mnt/teamsProjects/${projectId}/test /root/test`, // Bind project directory
        `--bind /mnt/teamsProjects/${projectId}/test /mnt/test`, // Bind project directory
        `--chdir /root`, // Start in user’s home directory
        //"--",
        "/bin/bash -c", // Start a new shell inside the bubblewrap container
        `echo \${PWD} &&`,
        `ls -la ~ &&`,
        `whoami &&`,
        `mount &&`,
        `echo "/mnt" &&`,
        `ls -la /mnt || true &&`,
        `echo "/mnt/test" &&`,
        `ls -la /mnt/test || true &&`,
        `echo "/mnt/teamsProjects" &&`,
        `ls -la /mnt/teamsProjects || true &&`,
        `"cd ~ && ${commandArgs}"` // Command to execute inside the shell
    ];
    return bubblewrap.join(" ");
};
```

The strange parts;
- `--tmpfs /mnt` does nothing, both on mac and linux `ls -la /mnt || true &&` shows `teamsProjects`.
- both `--bind`s does nothing, `ls -la ~ &&` missing the test dir, and `ls -la /mnt || true &&` has no test dir
- mount lists the `xx.xx.xx.xx:/xxxxx on /mnt type nfs4` mountpoint on linux, and `/host_mark/Users on /mnt type fakeowner (rw,nosuid,nodev,relatime,fakeowner)` on mac, to my understanding, these both should not be there
- I know mac messes up a lot of things with host<->container mounts (like you can list dirs after `chmod 111`), but not binding is strange, and I tested these on linux hosts too

**Comment by rusty-snake** [comment]
Can you give us the actually bwrap command line. You glue a string together meaning you will not pass it to a `execve()` like function but to a `system()` like function. Hence everything after `echo \${PWD}` is likely interpreted by this shell rather than being passed to bwrap.

**Comment by tg44** [comment]
You are right (next time I should go to sleep instead of posting)! I started to parenthesize things and it started to work. Now mount is failing to read mtab which is an expected behavior, and it seems everything is in its place. Sorry for bothering.
