### ISSUE TITLE
provide an option to set argv[0]

### ISSUE THREAD

**Issue by cgwalters** [containers/bubblewrap#91]
In some cases, programs vary behavior based on `argv[0]`, but we currently do:

```
  if (execvp (argv[0], argv) == -1)
```

requiring them to be the same.  We should add `--argv0 /usr/bin/blah` or so.

**Comment by cgwalters** [comment]
(I hit this when porting rpm-ostree code to use bwrap that had an API that took argv0 and char **argv separately, and while I think we can just conflate them, there's no reason not to support this)

**Comment by rhatdan** [comment]
Sounds reasonable.
